/* 영상 샷 도감 — 샷 데이터
   샷 1개 = 객체 1개. 카드 · 상세보기 · AI 프롬프트 · 샷 조합기가 모두 이 데이터에서 만들어집니다.

   필드
   - id / cat          URL 해시용 id (shots.html#low-angle), 분류 id (SHOT_CATEGORIES)
   - ko / en / abbr    한글 이름 / 영문 이름 / 약어
   - aka               다른 이름(검색 키워드)
   - media             { type: 'image', src } | { type: 'video', src, poster } | { type: 'cut', srcs: [...] } (컷 전환 시퀀스)
                       cut 은 hold(ms) · labels(컷마다 이름) · fade(디졸브처럼 겹치며 전환) 를 더 줄 수 있어요
   - draft             true 면 도감에 아직 보이지 않음 (예시 이미지 준비 중)
   - soon              true 면 지금은 이미지 예시, 나중에 영상으로 바꿀 샷 (카드에 "영상 준비 중" 표시)
   - summary           카드 한 줄 설명
   - feel              화면이 주는 느낌·효과
   - use               언제 쓰면 좋은지
   - tip               주의점
   - keyword           AI 영상 도구에 넣을 핵심 영어 키워드 (샷 조합기에서도 사용)
   - prompt            완성 영어 프롬프트. [SUBJECT] [LOCATION] 은 상세보기에서 원하는 대상·장소로 바뀝니다.
   - pairs             잘 어울리는 다른 샷 id
   - diagram           카메라 배치 도식 (size / angle / move, move 에 side: true 면 옆에서 본 그림) — 선택
   - guide             구도 가이드 선 (thirds / center / space / lines / diagonal) — 선택 */

window.SHOT_CATEGORIES = [
  { id: 'size', ko: '샷 크기', en: 'Shot Size' },
  { id: 'angle', ko: '카메라 앵글', en: 'Camera Angle' },
  { id: 'move', ko: '카메라 무빙', en: 'Camera Movement' },
  { id: 'comp', ko: '구도·프레이밍', en: 'Composition' },
  { id: 'people', ko: '인물·대화', en: 'People & Dialogue' },
  { id: 'lens', ko: '렌즈·초점', en: 'Lens & Focus' },
  { id: 'time', ko: '시간·속도', en: 'Time & Speed' },
  { id: 'edit', ko: '편집·연결', en: 'Editing' },
];

const IMG = (id) => ({ type: 'image', src: 'assets/shots/' + id + '.webp' });
const VID = (id) => ({ type: 'video', src: 'assets/shots/' + id + '.mp4', poster: 'assets/shots/' + id + '.webp' });
const CUT = (ids, hold, labels) => ({ type: 'cut', srcs: ids.map((id) => 'assets/shots/' + id + '.webp'), hold, labels });

window.SHOTS = [
  /* ───────────────────────── 샷 크기 ───────────────────────── */
  {
    id: 'extreme-wide', cat: 'size', ko: '익스트림 롱 샷', en: 'Extreme Wide Shot', abbr: 'EWS / ELS',
    aka: ['익스트림 와이드', 'Extreme Long Shot', '초원경'],
    media: IMG('extreme-wide'),
    summary: '인물은 아주 작고, 장소와 공간의 규모가 주인공이 되는 샷.',
    feel: '압도적인 스케일, 고독함, "여기가 어디인지"를 한눈에 알려줘요. 인물이 작을수록 세상에 비해 작고 외로워 보여요.',
    use: '영상 첫 장면, 장소가 바뀔 때, 여행·풍경 영상, 인물의 고립감을 보여줄 때',
    tip: '인물이 너무 작으면 누군지 모를 수 있어요. 옷 색(노란 우비처럼)으로 눈에 띄게 하고, 길게 보여주지 마세요.',
    keyword: 'extreme wide shot',
    prompt: 'Extreme wide shot from a high vantage point: [SUBJECT] appears very small in the center of the frame, dwarfed by [LOCATION]. Emphasize vast scale and atmosphere, cinematic lighting, slow and calm.',
    pairs: ['establishing', 'birds-eye', 'push-in'],
    diagram: { type: 'size', top: -1.6, bottom: 2.4 },
  },
  {
    id: 'full', cat: 'size', ko: '풀 샷', en: 'Full Shot', abbr: 'FS',
    aka: ['전신 샷', 'Wide Shot', 'Long Shot', '롱 샷'],
    media: { type: 'image', src: 'assets/shots/full.webp' },
    summary: '머리부터 발끝까지 인물 전체가 프레임에 딱 들어오는 샷.',
    feel: '인물의 옷차림·자세·몸짓과 주변 공간을 함께 보여줘요. 감정보다는 "이 사람이 이곳에 있다"는 상황 설명에 가까워요.',
    use: '인물 첫 등장, 의상·패션 영상, 춤·운동처럼 몸 전체 동작이 중요한 장면',
    tip: '발끝이 잘리지 않게 아래 여백을 조금 두세요. 머리 위 여백이 너무 크면 인물이 가라앉아 보여요.',
    keyword: 'full shot, full body in frame',
    prompt: 'Full shot showing [SUBJECT] from head to toe, standing in [LOCATION], eye-level camera, the whole body and outfit clearly visible with a little space around, cinematic composition.',
    pairs: ['medium', 'tracking', 'thirds'],
    diagram: { type: 'size', top: -0.08, bottom: 1.08 },
  },
  {
    id: 'cowboy', cat: 'size', ko: '미디엄 롱 샷 (카우보이)', en: 'Medium Long Shot / Cowboy Shot', abbr: 'MLS',
    aka: ['카우보이 샷', '니 샷', 'Knee Shot', '3/4 샷', 'American Shot'],
    media: IMG('cowboy'),
    summary: '허벅지 중간(무릎 위)부터 머리까지 담는 샷. 서부극에서 허리춤의 총까지 보여주려고 생겼어요.',
    feel: '당당하고 단단한 존재감. 몸짓과 표정이 함께 보여 "대치"나 "등장"의 긴장감을 줘요.',
    use: '두 사람이 마주 선 대치 장면, 히어로 등장, 패션 룩 소개, 단체 프로필',
    tip: '무릎 바로 위에서 자르면 어색해요. 허벅지 중간쯤에서 자르고, 손이 화면 안에 들어오게 하세요.',
    keyword: 'medium long shot, cowboy shot from mid-thigh up',
    prompt: 'Cowboy shot (medium long shot) of [SUBJECT] framed from mid-thigh up, standing confidently facing the camera in [LOCATION], hands visible, slight low angle, western standoff mood, cinematic.',
    pairs: ['full', 'low-angle', 'symmetry'],
    diagram: { type: 'size', top: -0.06, bottom: 0.72 },
  },
  {
    id: 'medium', cat: 'size', ko: '미디엄 샷', en: 'Medium Shot', abbr: 'MS',
    aka: ['허리 샷', 'Waist Shot', '바스트 샷 이전'],
    media: IMG('medium'),
    summary: '허리 위부터 머리까지, 가장 일상적이고 자연스러운 거리의 샷.',
    feel: '대화하는 사람과 마주한 듯 편안한 거리감. 표정과 손짓이 모두 보여서 정보 전달에 좋아요.',
    use: '인터뷰, 유튜브 토크, 대화 장면, 제품을 손에 들고 설명할 때',
    tip: '관절(허리·팔꿈치) 바로 위에서 자르면 어색해요. 허리 살짝 아래나 위에서 자르세요.',
    keyword: 'medium shot, waist up',
    prompt: 'Medium shot of [SUBJECT] from the waist up in [LOCATION], eye level, natural expression and hand gestures visible, background softly out of focus, cinematic.',
    pairs: ['two-shot', 'ots', 'shallow-dof'],
    diagram: { type: 'size', top: -0.06, bottom: 0.52 },
  },
  {
    id: 'mcu', cat: 'size', ko: '미디엄 클로즈업', en: 'Medium Close-up', abbr: 'MCU',
    aka: ['바스트 샷', 'Bust Shot', '가슴 위 샷', '인터뷰 샷'],
    media: IMG('mcu'),
    summary: '가슴 위부터 머리까지. 인터뷰·브이로그에서 가장 많이 쓰는 기본 샷.',
    feel: '표정이 잘 보이면서도 답답하지 않은 거리. 말하는 사람에게 자연스럽게 집중하게 돼요.',
    use: '인터뷰, 유튜브·브이로그 토크, 뉴스, 대화 장면에서 말하는 사람',
    tip: '눈이 화면 위쪽 1/3 선에 오게 하세요. 머리 위 여백이 너무 크면 인물이 작아 보여요.',
    keyword: 'medium close-up, chest up',
    prompt: 'Medium close-up of [SUBJECT] from the chest up in [LOCATION], eye level, looking just off-camera as if talking in an interview, eyes on the upper third, soft background bokeh, cinematic.',
    pairs: ['medium', 'close-up', 'shallow-dof'],
    diagram: { type: 'size', top: -0.05, bottom: 0.34 },
  },
  {
    id: 'close-up', cat: 'size', ko: '클로즈업', en: 'Close-up', abbr: 'CU',
    aka: ['얼굴 샷', '근접 샷', 'Tight Shot'],
    media: IMG('close-up'),
    summary: '얼굴(또는 대상)이 화면을 가득 채우는 샷. 감정이 가장 잘 보여요.',
    feel: '감정 몰입, 긴장감, 친밀함. 관객이 인물의 마음속으로 들어가는 느낌을 줘요.',
    use: '감정이 터지는 순간, 중요한 대사, 리액션, 제품 디테일 강조',
    tip: '너무 자주 쓰면 효과가 떨어져요. 넓은 샷 사이에 결정적인 순간에만 넣으세요.',
    keyword: 'close-up shot of the face',
    prompt: 'Close-up shot of [SUBJECT]\'s face filling the frame in [LOCATION], subtle emotional expression, detailed skin and texture, soft cinematic light on the face, shallow depth of field.',
    pairs: ['push-in', 'slow-mo', 'shallow-dof'],
    diagram: { type: 'size', top: -0.04, bottom: 0.22 },
  },
  {
    id: 'ecu', cat: 'size', ko: '익스트림 클로즈업', en: 'Extreme Close-up', abbr: 'ECU / XCU',
    aka: ['초접사', '눈 클로즈업', 'Macro Close-up', '디테일 클로즈업'],
    media: IMG('ecu'),
    summary: '눈·입술처럼 얼굴의 한 부분만 화면을 가득 채우는 샷.',
    feel: '숨 막히는 긴장감과 강렬함. 아주 작은 감정 변화(눈동자 떨림)까지 크게 보여줘요.',
    use: '결정적 순간 직전의 긴장, 스릴러·액션의 대치, 뷰티(속눈썹·립) 광고',
    tip: '맥락 없이 쓰면 무슨 장면인지 몰라요. 넓은 샷 → 클로즈업 → 익스트림 클로즈업 순서로 좁혀 가세요.',
    keyword: 'extreme close-up of the eyes',
    prompt: 'Extreme close-up of only [SUBJECT]\'s eyes filling the whole frame in [LOCATION], tiny details of eyelashes and irises, reflections in the eyes, intense and tense, cinematic.',
    pairs: ['close-up', 'push-in', 'macro'],
    diagram: { type: 'size', top: 0.035, bottom: 0.1 },
  },
  {
    id: 'insert', cat: 'size', ko: '인서트', en: 'Insert Shot', abbr: 'Insert',
    aka: ['디테일 샷', 'Detail Shot', 'B-roll', '손 샷'],
    media: IMG('insert'),
    summary: '손·휴대폰 화면·시계처럼 이야기에 중요한 작은 물건을 크게 보여주는 샷.',
    feel: '"이게 중요해"라고 관객에게 짚어줘요. 정보 전달과 리듬 조절에 좋아요.',
    use: '문자 메시지·편지 보여주기, 제품 디테일, 요리 손 동작, 편집 사이를 메우는 B-roll',
    tip: '앞뒤 샷과 조명·소품이 맞아야 해요(연속성). 1~2초면 충분해요.',
    keyword: 'insert shot, tight detail of the hands and object',
    prompt: 'Insert shot: a tight detail of [SUBJECT]\'s hand holding a glowing smartphone in [LOCATION], only the hand and object in frame, no face, shallow depth of field, cinematic.',
    pairs: ['close-up', 'cutaway', 'macro'],
  },

  /* ───────────────────────── 카메라 앵글 ───────────────────────── */
  {
    id: 'high-angle', cat: 'angle', ko: '하이 앵글', en: 'High Angle', abbr: 'HA',
    aka: ['부감', '내려다보기', 'Looking Down'],
    media: IMG('high-angle'),
    summary: '카메라가 인물보다 높은 곳에서 내려다보는 샷.',
    feel: '인물이 작고 약해 보여요. 외로움, 무력감, 관찰당하는 느낌, 또는 귀여움을 줄 수 있어요.',
    use: '인물이 위기에 처했을 때, 패배·좌절 장면, 아이·반려동물을 귀엽게, 상황 전체를 내려다볼 때',
    tip: '각도가 너무 크면(거의 수직) 버즈아이 뷰가 돼요. 감정을 담으려면 30~45도 정도가 좋아요.',
    keyword: 'high angle shot, camera looking down',
    prompt: 'High angle shot: the camera is above [SUBJECT] looking down at about 45 degrees in [LOCATION], the subject looks up toward the camera and appears small and vulnerable, cinematic.',
    pairs: ['negative-space', 'close-up'],
    diagram: { type: 'angle', cam: 'high' },
  },
  {
    id: 'low-angle', cat: 'angle', ko: '로우 앵글', en: 'Low Angle', abbr: 'LA',
    aka: ['앙각', '올려다보기', 'Looking Up', 'Hero Shot'],
    media: IMG('low-angle'),
    summary: '카메라가 낮은 곳에서 인물을 올려다보는 샷.',
    feel: '인물이 크고 강하고 위압적으로 보여요. 자신감, 권위, 영웅적인 느낌.',
    use: '주인공 등장, 승리·결심의 순간, 악역의 위압감, 제품·건물을 웅장하게',
    tip: '광각 렌즈로 너무 가까이서 찍으면 얼굴(턱·코)이 왜곡돼요. 조금 떨어져서 찍으세요.',
    keyword: 'low angle shot, camera looking up',
    prompt: 'Low angle hero shot: the camera is near knee height looking up at [SUBJECT] in [LOCATION], the subject towers over the camera, powerful and confident, dramatic sky and tall background, cinematic.',
    pairs: ['slow-mo', 'push-in', 'wide-angle'],
    diagram: { type: 'angle', cam: 'low' },
  },
  {
    id: 'birds-eye', cat: 'angle', ko: '버즈아이 뷰', en: "Bird's-eye View", abbr: 'Top Shot',
    aka: ['탑 뷰', '오버헤드 샷', 'Overhead Shot', '부감 수직'],
    media: IMG('birds-eye'),
    summary: '카메라가 바로 위에서 수직으로 내려다보는 샷.',
    feel: '지도나 무대처럼 그래픽적인 화면. 신의 시점, 운명, 패턴의 아름다움을 보여줘요.',
    use: '음식·책상 위 플랫레이, 도시·도로 패턴, 인물의 위치 관계, 장면 전환용',
    tip: '그림자와 색 대비가 강해야 평면적이지 않아요. 드론이나 높은 곳에서 수직을 정확히 맞추세요.',
    keyword: "bird's-eye view, top-down overhead shot",
    prompt: "Bird's-eye view: the camera is directly overhead looking straight down at [SUBJECT] in [LOCATION], graphic top-down composition, strong shapes, shadows and color contrast, cinematic.",
    pairs: ['extreme-wide', 'match-cut', 'tilt-shift'],
    diagram: { type: 'angle', cam: 'top' },
  },
  {
    id: 'dutch', cat: 'angle', ko: '더치 앵글', en: 'Dutch Angle', abbr: 'Dutch Tilt',
    aka: ['캔티드 앵글', 'Canted Angle', '기울인 화면', '사선 구도'],
    media: IMG('dutch'),
    summary: '카메라를 옆으로 기울여 수평선이 사선이 되는 샷.',
    feel: '불안, 혼란, 긴장, 뭔가 잘못된 느낌. 세상이 기울어진 듯한 심리 상태를 표현해요.',
    use: '스릴러·호러, 인물이 혼란스럽거나 취했을 때, 뮤직비디오의 역동적인 연출',
    tip: '남발하면 어지럽고 촌스러워 보여요. 감정이 흔들리는 장면에만 쓰고 기울기는 10~25도가 적당해요.',
    keyword: 'dutch angle, canted tilted camera',
    prompt: 'Dutch angle shot: the camera is tilted about 20 degrees so the horizon and lines of [LOCATION] run diagonally, [SUBJECT] looks tense and uneasy, disorienting psychological mood, cinematic.',
    pairs: ['close-up', 'jump-cut', 'wide-angle'],
    diagram: { type: 'angle', cam: 'tilt' },
  },
  {
    id: 'worms-eye', cat: 'angle', ko: '웜즈아이 뷰', en: "Worm's-eye View", abbr: "Worm's Eye",
    aka: ['앙각 수직', '바닥에서 올려다보기', 'Extreme Low Angle', '개미 시점'],
    media: IMG('worms-eye'),
    summary: '바닥에 카메라를 두고 거의 수직으로 올려다보는 극단적인 로우 앵글.',
    feel: '압도적인 위압감과 스케일. 인물·건물이 하늘을 찌를 듯 거대해 보여요.',
    use: '거대한 건물·나무, 히어로·악역의 압도적 등장, 넘어진 사람 시점, 뮤직비디오',
    tip: '광각 렌즈와 함께 쓰면 선이 하늘로 모여 더 극적이에요. 너무 오래 보여주면 어지러워요.',
    keyword: "worm's-eye view, camera on the ground looking straight up",
    prompt: "Worm's-eye view: the camera lies on the ground of [LOCATION] pointing almost straight up at [SUBJECT] standing over the lens, tall buildings converging toward the sky behind, extreme perspective, cinematic.",
    pairs: ['low-angle', 'wide-angle', 'birds-eye'],
    diagram: { type: 'angle', cam: 'worm' },
  },
  {
    id: 'eye-level', cat: 'angle', ko: '아이 레벨', en: 'Eye Level', abbr: 'EL',
    aka: ['눈높이 샷', '수평 앵글', 'Neutral Angle'],
    media: IMG('eye-level'),
    summary: '인물의 눈높이에서 수평으로 찍는, 가장 중립적인 기준 앵글.',
    feel: '관객과 인물이 대등한 관계. 꾸밈없고 솔직하며 편안해요.',
    use: '인터뷰, 일상 대화, 다큐멘터리, 하이·로우 앵글과 대비시키는 기준 샷',
    tip: '중립적이라 밋밋할 수 있어요. 구도(3분할)나 조명으로 재미를 더하세요.',
    keyword: 'eye-level shot, straight-on camera',
    prompt: 'Eye-level shot: the camera at exactly the eye height of [SUBJECT], straight-on and level in [LOCATION], the subject looks directly at the camera, calm and honest, horizon perfectly level, cinematic.',
    pairs: ['medium', 'mcu', 'symmetry'],
    diagram: { type: 'angle', cam: 'eye' },
  },
  {
    id: 'ground-level', cat: 'angle', ko: '그라운드 레벨', en: 'Ground Level Shot', abbr: 'Ground',
    aka: ['로우 그라운드', '바닥 샷', 'Floor Level', '발 샷'],
    media: IMG('ground-level'),
    summary: '카메라를 바닥에 붙여 땅 높이에서 수평으로 보는 샷.',
    feel: '발걸음·물웅덩이·바퀴처럼 평소에 안 보이는 세계가 크게 보여요. 생동감과 긴장.',
    use: '걷기 시작하는 발, 물이 튀는 순간, 자동차·스케이트보드, 반려동물 시점',
    tip: '바닥이 화면 아래를 크게 차지하니 바닥 질감(젖은 아스팔트·조명 반사)이 예뻐야 해요.',
    keyword: 'ground-level shot, camera on the floor',
    prompt: 'Ground-level shot: the camera sits right on the wet ground of [LOCATION], [SUBJECT]\'s feet step into a puddle in the foreground with a splash, the rest of the scene softly blurred behind, cinematic.',
    pairs: ['insert', 'tracking', 'slow-mo'],
    diagram: { type: 'angle', cam: 'ground' },
  },
  {
    id: 'shoulder-level', cat: 'angle', ko: '숄더 레벨', en: 'Shoulder Level Shot', abbr: 'Shoulder',
    aka: ['어깨 높이 샷', 'Shoulder Height'],
    media: IMG('shoulder-level'),
    summary: '어깨 높이(눈보다 살짝 아래)에서 찍어 인물이 조금 더 단단해 보이는 앵글.',
    feel: '아이 레벨보다 살짝 강하고 영웅적인 느낌. 과하지 않은 존재감.',
    use: '액션 영화의 인물 샷, 대치 장면, 자신감 있는 인물 소개',
    tip: '로우 앵글처럼 과장되지 않아 자연스러워요. 화려한 무빙과 함께 쓰기 좋아요.',
    keyword: 'shoulder-level shot, slightly below eye level',
    prompt: 'Shoulder-level shot: the camera at the shoulder height of [SUBJECT], slightly below the eyes, medium shot in [LOCATION] as the subject turns their head over the shoulder, action-movie tension, cinematic.',
    pairs: ['eye-level', 'low-angle', 'handheld'],
    diagram: { type: 'angle', cam: 'shoulder' },
  },

  /* ───────────────────────── 카메라 무빙 ───────────────────────── */
  {
    id: 'push-in', cat: 'move', ko: '푸시 인 (달리 인)', en: 'Push In / Dolly In', abbr: 'Dolly In',
    aka: ['달리 인', '카메라 전진', 'Slow Push', '트랙 인'],
    media: VID('push-in'),
    summary: '카메라가 인물 쪽으로 천천히 다가가는 무빙.',
    feel: '긴장과 집중이 점점 커져요. 인물의 깨달음, 결심, 감정의 고조를 관객이 함께 느끼게 해요.',
    use: '중요한 대사·깨달음의 순간, 인물 소개, 광고 마지막 제품 강조',
    tip: '줌(Zoom)과 달라요. 줌은 렌즈만 당겨 원근감이 그대로지만, 푸시인은 카메라가 실제로 움직여 배경과의 거리감이 변해요.',
    keyword: 'slow dolly push-in',
    prompt: 'Slow dolly push-in: the camera moves steadily forward from a full shot toward [SUBJECT]\'s face in [LOCATION], ending in a close-up. Smooth cinematic camera move, one continuous shot, no cuts.',
    pairs: ['close-up', 'low-angle', 'shallow-dof'],
    diagram: { type: 'move', path: 'push' },
  },
  {
    id: 'pan', cat: 'move', ko: '팬', en: 'Pan', abbr: 'Pan L/R',
    aka: ['패닝', '좌우 회전', 'Panning Shot'],
    media: VID('pan'),
    summary: '카메라 위치는 고정한 채 좌우로 고개를 돌리는 무빙.',
    feel: '관객이 고개를 돌려 주변을 둘러보는 느낌. 공간을 소개하거나 무언가를 "발견"하게 만들어요.',
    use: '풍경·공간 소개, 인물이나 물건을 드러내는(리빌) 장면, 움직이는 대상 따라가기',
    tip: '카메라가 옆으로 "이동"하면 트럭(Truck), 제자리에서 "회전"하면 팬이에요. AI 에는 fixed position, rotates 처럼 명확히 쓰세요.',
    keyword: 'slow pan left to right, fixed camera position',
    prompt: 'Slow horizontal camera pan from left to right on a fixed tripod: the shot starts on [LOCATION] and pans to reveal [SUBJECT]. The camera position stays fixed and only rotates. One continuous shot, no cuts.',
    pairs: ['extreme-wide', 'establishing'],
    diagram: { type: 'move', path: 'pan' },
  },
  {
    id: 'tracking', cat: 'move', ko: '트래킹 샷', en: 'Tracking Shot', abbr: 'Follow Shot',
    aka: ['팔로우 샷', '추적 샷', 'Follow Cam', '리딩 샷'],
    media: VID('tracking'),
    summary: '걷거나 달리는 인물과 같은 속도로 카메라가 함께 이동하는 무빙.',
    feel: '관객이 인물과 함께 걷는 듯한 몰입감과 생동감. 이야기가 앞으로 나아가는 느낌.',
    use: '걸으며 말하는 장면, 브이로그, 추격·이동 장면, 패션 런웨이',
    tip: '앞에서 뒤로 물러나며 찍으면 "리딩", 뒤에서 따라가면 "팔로우"예요. 짐벌·스테디캠으로 흔들림을 줄이세요.',
    keyword: 'tracking shot, camera moves backward with the walking subject',
    prompt: 'Tracking shot: the camera moves backward in front of [SUBJECT] at walking pace as the subject walks toward the camera through [LOCATION], keeping them medium-full in frame, steady gimbal movement. One continuous shot, no cuts.',
    pairs: ['full', 'speed-ramp'],
    diagram: { type: 'move', path: 'track' },
  },
  {
    id: 'orbit', cat: 'move', ko: '오빗 샷', en: 'Orbit / Arc Shot', abbr: 'Arc',
    aka: ['아크 샷', '360 샷', '회전 샷', 'Circle Shot'],
    media: VID('orbit'),
    summary: '카메라가 인물 주위를 원을 그리며 도는 무빙.',
    feel: '인물이 세계의 중심이 된 듯한 극적인 순간. 감정의 절정, 히어로 모먼트에 강해요.',
    use: '주인공의 결정적 순간, 재회·고백, 제품 360도 소개, 뮤직비디오',
    tip: '배경이 회전해야 효과가 커요. 인물 뒤에 조명·간판 같은 포인트가 있으면 회전이 잘 보여요.',
    keyword: 'orbit shot, camera circles around the subject',
    prompt: 'Orbit shot: the camera circles smoothly about 180 degrees around [SUBJECT] at eye level while they stand still in [LOCATION]; the background rotates behind them. Smooth arc camera movement, one continuous shot, no cuts.',
    pairs: ['low-angle', 'slow-mo'],
    diagram: { type: 'move', path: 'orbit' },
  },
  {
    id: 'tilt', cat: 'move', ko: '틸트', en: 'Tilt Up / Down', abbr: 'Tilt',
    aka: ['틸트 업', '틸트 다운', '상하 회전', 'Tilt Up'],
    media: CUT(['tilt-a', 'tilt-b'], 1400, ['시작', '끝']), soon: true,
    summary: '카메라 위치는 그대로, 위아래로 고개를 드는(내리는) 무빙.',
    feel: '발끝부터 얼굴까지 천천히 드러내면 "누구지?" 하는 기대감. 위로 올리면 웅장함.',
    use: '인물 등장(발 → 얼굴), 높은 건물 올려다보기, 하늘에서 땅으로 내려오는 오프닝',
    tip: '팬의 세로 버전이에요. 위로 "이동"하면 페데스탈, 제자리 "회전"이면 틸트예요.',
    keyword: 'slow tilt up from feet to face, fixed camera position',
    prompt: 'Slow vertical tilt up on a fixed tripod: the shot starts on [SUBJECT]\'s feet on the wet ground of [LOCATION] and tilts up to reveal their face. The camera position stays fixed and only rotates. One continuous shot, no cuts.',
    pairs: ['pan', 'low-angle', 'pedestal'],
    diagram: { type: 'move', path: 'tilt', side: true },
  },
  {
    id: 'pull-back', cat: 'move', ko: '풀백 리빌 (달리 아웃)', en: 'Pull Back Reveal / Dolly Out', abbr: 'Dolly Out',
    aka: ['달리 아웃', '풀 아웃', '리빌 샷', 'Pull Out', 'Reveal Shot'],
    media: CUT(['pull-back-a', 'pull-back-b'], 1400, ['시작', '끝']), soon: true,
    summary: '가까이에서 시작해 카메라가 뒤로 물러나며 주변 상황을 드러내는 무빙.',
    feel: '"사실은 이런 상황이었어" 하는 반전과 고립감. 엔딩에 쓰면 여운이 남아요.',
    use: '영화 엔딩, 반전 공개, 인물의 외로움, 감정에서 상황으로 넘어갈 때',
    tip: '푸시 인의 반대예요. 마지막에 드러나는 장면이 놀라울수록 효과가 커요.',
    keyword: 'slow dolly out pull-back reveal',
    prompt: 'Slow dolly pull-back: the shot starts on a close-up of [SUBJECT]\'s face and the camera moves steadily backward and up, revealing they are alone in the middle of a vast [LOCATION]. One continuous shot, no cuts.',
    pairs: ['push-in', 'extreme-wide', 'crane'],
    diagram: { type: 'move', path: 'pull' },
  },
  {
    id: 'dolly-zoom', cat: 'move', ko: '돌리 줌 (버티고)', en: 'Dolly Zoom / Vertigo Effect', abbr: 'Vertigo',
    aka: ['버티고 샷', '히치콕 줌', '컨트라 줌', 'Zolly', 'Contra-zoom'],
    media: CUT(['dolly-zoom-a', 'dolly-zoom-b'], 1300, ['망원 (시작)', '광각 (끝)']), soon: true,
    summary: '카메라는 뒤로 빠지면서 렌즈는 당겨, 인물 크기는 그대로인데 배경만 늘어나는 효과.',
    feel: '현기증, 충격, 깨달음. 세상이 일그러지는 듯한 심리적 충격을 줘요.',
    use: '충격적인 사실을 알게 된 순간, 공포·불안, 높은 곳의 현기증, 패러디',
    tip: 'AI 영상 모델이 정확히 만들기 어려워요. "subject stays the same size, background stretches" 를 꼭 넣고 여러 번 뽑아 보세요.',
    keyword: 'dolly zoom vertigo effect, background stretches while subject stays the same size',
    prompt: 'Dolly zoom (vertigo effect): the camera dollies backward while zooming in, so [SUBJECT] stays exactly the same size in the center of frame while [LOCATION] behind them stretches away and warps, unsettling shock. One continuous shot, no cuts.',
    pairs: ['push-in', 'close-up', 'telephoto'],
    diagram: { type: 'move', path: 'vertigo' },
  },
  {
    id: 'crane', cat: 'move', ko: '크레인 샷', en: 'Crane / Jib Shot', abbr: 'Crane',
    aka: ['지브 샷', '붐 샷', '크레인 업', 'Jib Up', 'Boom Shot'],
    media: CUT(['crane-a', 'crane-b'], 1400, ['시작', '끝']), soon: true,
    summary: '크레인 팔에 카메라를 달아 높이 솟아오르거나 내려오는 큰 무빙.',
    feel: '웅장하고 서사적인 느낌. 솟아오르면 "이야기의 끝", 내려오면 "이야기의 시작".',
    use: '영화 오프닝·엔딩, 콘서트·행사 전경, 감정에서 풍경으로 넓어질 때',
    tip: '수직으로만 오르면 페데스탈, 크게 호를 그리며 오르면 크레인이에요. 드론으로 비슷하게 찍기도 해요.',
    keyword: 'crane shot rising up and away',
    prompt: 'Crane shot: the camera starts at ground level near [SUBJECT] and rises smoothly high into the air in a sweeping arc, looking down as [LOCATION] spreads out below. Grand cinematic camera move, one continuous shot, no cuts.',
    pairs: ['pull-back', 'drone', 'establishing'],
    diagram: { type: 'move', path: 'crane', side: true },
  },
  {
    id: 'handheld', cat: 'move', ko: '핸드헬드', en: 'Handheld Shot', abbr: 'Handheld',
    aka: ['들고 찍기', '흔들리는 카메라', 'Shaky Cam', '다큐 스타일'],
    media: IMG('handheld'), soon: true,
    summary: '삼각대 없이 손으로 들고 찍어 자연스럽게 흔들리는 화면.',
    feel: '날것의 현장감, 긴박함, 불안. 실제로 그 자리에 있는 것 같은 다큐 느낌.',
    use: '다큐멘터리, 추격·싸움·재난 장면, 브이로그, 혼란스러운 감정',
    tip: '너무 흔들면 멀미가 나요. AI 에는 subtle handheld shake 처럼 강도를 함께 쓰세요.',
    keyword: 'handheld camera, subtle natural shake',
    prompt: 'Handheld documentary-style shot: the camera operator moves alongside [SUBJECT] as they walk quickly through [LOCATION], natural subtle camera shake, slightly off-balance framing, raw and urgent. One continuous shot, no cuts.',
    pairs: ['pov', 'tracking', 'jump-cut'],
    diagram: { type: 'move', path: 'shake' },
  },
  {
    id: 'drone', cat: 'move', ko: '드론 샷', en: 'Drone Shot', abbr: 'Aerial',
    aka: ['에어리얼 샷', '항공 촬영', 'Aerial Shot', 'Flyover'],
    media: IMG('drone'), soon: true,
    summary: '하늘을 나는 드론으로 넓은 공간을 부드럽게 날아가며 찍는 샷.',
    feel: '시원하고 자유로운 개방감, 장소의 규모. 영화 같은 고급스러움.',
    use: '여행·부동산·자연 영상, 오프닝, 자동차 추격, 인물을 하늘에서 따라가기',
    tip: '천천히 일정한 속도로 날아야 고급스러워요. 앞으로 + 살짝 내려가기처럼 동작을 하나만 정하세요.',
    keyword: 'aerial drone shot flying forward',
    prompt: 'Aerial drone shot flying slowly forward high above [LOCATION], following [SUBJECT] walking far below as a small figure, smooth stable flight, wide cinematic view. One continuous shot, no cuts.',
    pairs: ['establishing', 'birds-eye', 'crane'],
    diagram: { type: 'move', path: 'fly' },
  },
  {
    id: 'fpv', cat: 'move', ko: 'FPV 드론', en: 'FPV Drone Shot', abbr: 'FPV',
    aka: ['레이싱 드론', '1인칭 드론', 'Cinewhoop', 'FPV Dive'],
    media: IMG('fpv'), soon: true,
    summary: '작고 빠른 레이싱 드론으로 건물 사이를 파고들고 급강하하는 역동적인 샷.',
    feel: '롤러코스터 같은 속도감과 짜릿함. 한 번에 공간을 꿰뚫는 원테이크 느낌.',
    use: '자동차·스포츠 광고, 건물·매장 원테이크 투어, 액션, 쇼츠 오프닝',
    tip: '속도·기울기(뱅킹)가 핵심 단어예요. 화면 끝 모션 블러를 함께 쓰면 더 빨라 보여요.',
    keyword: 'FPV drone diving fast and low, banking turns',
    prompt: 'FPV drone shot: a racing drone dives fast and low between buildings of [LOCATION], banking through tight turns and swooping toward [SUBJECT], motion blur at the edges, wide lens, adrenaline speed. One continuous shot, no cuts.',
    pairs: ['drone', 'speed-ramp', 'wide-angle'],
    diagram: { type: 'move', path: 'fpv' },
  },
  {
    id: 'truck', cat: 'move', ko: '트럭', en: 'Truck Left / Right', abbr: 'Truck',
    aka: ['트러킹', '수평 이동', '슬라이더 샷', 'Crab Shot', 'Slider'],
    media: CUT(['truck-a', 'truck-b'], 1400, ['시작', '끝']), soon: true,
    summary: '카메라 전체가 옆으로 평행하게 미끄러지는 무빙. 앞뒤 사물이 다른 속도로 움직여요.',
    feel: '시차(패럴랙스) 덕분에 입체감이 살아나고, 무언가가 서서히 드러나는 세련된 느낌.',
    use: '제품 소개, 기둥·사람 뒤에서 인물 드러내기, 진열된 물건 훑기, 인테리어',
    tip: '팬(제자리 회전)과 헷갈리기 쉬워요. 앞쪽에 기둥·화분 같은 전경을 두면 이동이 확실히 보여요.',
    keyword: 'camera trucks right on a slider, parallax',
    prompt: 'Truck shot: the camera slides sideways to the right on a slider past a dark pillar in the foreground, revealing [SUBJECT] standing in [LOCATION], strong parallax between foreground and background. One continuous shot, no cuts.',
    pairs: ['pan', 'foreground', 'tracking'],
    diagram: { type: 'move', path: 'truck' },
  },
  {
    id: 'pedestal', cat: 'move', ko: '페데스탈', en: 'Pedestal Up / Down', abbr: 'Ped',
    aka: ['붐 업', '수직 이동', 'Ped Up', 'Boom Up'],
    media: CUT(['pedestal-a', 'pedestal-b'], 1400, ['시작', '끝']), soon: true,
    summary: '카메라 각도는 그대로, 높이만 위아래로 수직 이동하는 무빙.',
    feel: '시선이 같은 각도로 차분히 올라가며 정보가 하나씩 드러나요. 틸트보다 담백해요.',
    use: '손 → 얼굴로 올라가기, 책상 위 → 인물, 제품 진열대 위아래 훑기',
    tip: '각도가 바뀌면 틸트가 섞인 거예요. AI 에는 the camera rises vertically, staying level 처럼 쓰세요.',
    keyword: 'pedestal up, the camera rises vertically staying level',
    prompt: 'Pedestal shot: the camera rises straight up vertically while staying level, from [SUBJECT]\'s hands at waist height to their face, straight-on in [LOCATION]. No tilting. One continuous shot, no cuts.',
    pairs: ['tilt', 'crane', 'insert'],
    diagram: { type: 'move', path: 'pedestal', side: true },
  },
  {
    id: 'zoom', cat: 'move', ko: '줌 인 / 줌 아웃', en: 'Zoom In / Out', abbr: 'Zoom',
    aka: ['크래시 줌', '스냅 줌', 'Crash Zoom', 'Snap Zoom'],
    media: CUT(['zoom-a', 'zoom-b'], 1300, ['줌 전 (와이드)', '줌 후 (망원)']), soon: true,
    summary: '카메라는 고정, 렌즈 화각만 바꿔 확대·축소하는 연출.',
    feel: '천천히 하면 관찰·몰입, 빠르게(크래시 줌) 하면 코믹하거나 충격적인 강조.',
    use: '예능·유튜브 강조, 70년대 영화 느낌, 멀리 있는 대상 갑자기 강조, 다큐 관찰',
    tip: '푸시 인과 달리 원근감(배경 크기 비율)이 그대로예요. "cinematic"을 원하면 푸시 인, "강조·코믹"이면 줌.',
    keyword: 'fast crash zoom in, static camera',
    prompt: 'Static camera with a fast crash zoom: the lens zooms in quickly from a wide view of [LOCATION] to a tight shot of [SUBJECT]\'s face. The camera does not move, only the lens zooms. One continuous shot, no cuts.',
    pairs: ['push-in', 'telephoto', 'jump-cut'],
    diagram: { type: 'move', path: 'zoom' },
  },
  {
    id: 'whip-pan', cat: 'move', ko: '휩 팬', en: 'Whip Pan', abbr: 'Whip',
    aka: ['스위시 팬', '플래시 팬', 'Swish Pan', 'Flash Pan'],
    media: IMG('whip-pan'), soon: true,
    summary: '카메라를 아주 빠르게 휙 돌려 화면이 가로로 번지는 무빙.',
    feel: '에너지와 속도, 시선이 확 옮겨지는 느낌. 두 대상 사이의 긴장이나 장면 전환에 좋아요.',
    use: '대화 중 시선 이동, 장면 전환(휩 트랜지션), 액션·코미디, 뮤직비디오',
    tip: '번짐이 충분해야 컷이 숨겨져요. 전환용이면 다음 장면도 같은 방향으로 휩해서 시작하세요.',
    keyword: 'whip pan, extremely fast pan with motion blur',
    prompt: 'Whip pan: the camera swings extremely fast from left to right away from [SUBJECT] in [LOCATION], the frame smears into horizontal motion blur streaks. One continuous shot, no cuts.',
    pairs: ['pan', 'whip-transition', 'speed-ramp'],
    diagram: { type: 'move', path: 'whip' },
  },

  /* ───────────────────────── 구도·프레이밍 ───────────────────────── */
  {
    id: 'thirds', cat: 'comp', ko: '3분할 구도', en: 'Rule of Thirds', abbr: 'Thirds',
    aka: ['삼분할', '황금분할 비슷', 'Off-center Framing'],
    media: IMG('thirds'),
    summary: '화면을 가로·세로 3등분한 선 위에 인물을 두는 가장 기본 구도.',
    feel: '안정적이면서도 정중앙보다 자연스럽고 여유 있는 느낌. 인물이 바라보는 쪽에 공간이 생겨요.',
    use: '대부분의 인물·풍경 샷, 인터뷰, 인물이 무언가를 바라보는 장면',
    tip: '인물이 바라보는(또는 걸어가는) 방향에 빈 공간(룩 룸)을 두세요. 반대로 두면 답답하고 불안해 보여요.',
    keyword: 'rule of thirds composition, subject on the left third',
    prompt: 'Rule-of-thirds composition: [SUBJECT] stands on the left vertical third line of the frame in [LOCATION], with open space and leading light toward the right two thirds, cinematic.',
    pairs: ['full', 'negative-space'],
    guide: 'thirds',
  },
  {
    id: 'symmetry', cat: 'comp', ko: '중앙 대칭 구도', en: 'Symmetrical Composition', abbr: 'Center',
    aka: ['대칭 구도', '센터 프레이밍', '웨스 앤더슨 구도', 'Centered Framing'],
    media: IMG('symmetry'),
    summary: '인물을 정중앙에, 양쪽 배경을 거울처럼 맞춘 구도.',
    feel: '단단하고 의도적인 느낌, 정적인 긴장감, 동화나 그림 같은 미장센.',
    use: '인물 소개 엔딩 컷, 건축·인테리어, 스타일리시한 광고, 정면 대치 장면',
    tip: '조금만 어긋나도 실수처럼 보여요. 수평·수직을 정확히 맞추고, 소실점을 인물 뒤에 두세요.',
    keyword: 'perfectly symmetrical centered composition',
    prompt: 'Perfectly symmetrical centered composition: [SUBJECT] stands exactly in the center of [LOCATION], the background mirrored on both sides, the vanishing point directly behind the subject, static camera, cinematic.',
    pairs: ['push-in', 'establishing'],
    guide: 'center',
  },
  {
    id: 'frame-in-frame', cat: 'comp', ko: '프레임 속 프레임', en: 'Frame within a Frame', abbr: 'FiF',
    aka: ['액자 구도', '이중 프레임', 'Natural Frame'],
    media: IMG('frame-in-frame'),
    summary: '문·창문·터널 같은 사물로 인물을 한 번 더 둘러싸는 구도.',
    feel: '시선이 인물에게 집중되고, 엿보는 듯한 관음적 느낌이나 갇힌 느낌, 깊이감을 줘요.',
    use: '인물을 관찰하는 시점, 고립·갇힘 표현, 공간의 깊이를 보여줄 때',
    tip: '앞쪽 프레임(문틀)은 어둡게, 인물 쪽은 밝게 하면 시선이 확실히 모여요.',
    keyword: 'frame within a frame, shot through a doorway',
    prompt: 'Frame within a frame: shot from inside a dark interior through a doorway or window; the bright opening frames [SUBJECT] standing in [LOCATION] beyond, strong depth and contrast, cinematic.',
    pairs: ['negative-space', 'symmetry'],
    guide: 'frame',
  },
  {
    id: 'negative-space', cat: 'comp', ko: '네거티브 스페이스', en: 'Negative Space', abbr: 'Empty Space',
    aka: ['여백 구도', '빈 공간', 'Minimal Composition'],
    media: IMG('negative-space'),
    summary: '인물은 작게 구석에, 화면 대부분을 비워 두는 구도.',
    feel: '고요함, 외로움, 그리움, 생각에 잠긴 느낌. 빈 공간이 감정을 대신 말해요.',
    use: '감성 영상, 이별·그리움 장면, 자막·카피를 넣을 공간이 필요한 광고',
    tip: '빈 공간에도 질감(하늘·안개·빛)이 있어야 허전하지 않아요. 글자를 넣을 자리로도 좋아요.',
    keyword: 'negative space composition, small subject in the corner',
    prompt: 'Minimal negative space composition: [SUBJECT] is small in the lower right corner, a large empty area of [LOCATION] fills the rest of the frame, quiet and lonely mood, cinematic.',
    pairs: ['extreme-wide', 'high-angle'],
    guide: 'space',
  },
  {
    id: 'leading-lines', cat: 'comp', ko: '리딩 라인', en: 'Leading Lines', abbr: 'Lines',
    aka: ['유도선 구도', '선 구도', '소실점 구도', 'Vanishing Point'],
    media: IMG('leading-lines'),
    summary: '길·레일·난간 같은 선이 시선을 인물에게 끌고 가는 구도.',
    feel: '관객 눈이 자연스럽게 인물에게 도착해요. 깊이감과 방향감, 여정의 느낌.',
    use: '길 위의 인물, 건축·도시, 여행 영상, 인물을 작게 두면서도 주목시킬 때',
    tip: '선이 모이는 소실점에 인물을 두세요. 선이 화면 모서리에서 시작하면 더 강해요.',
    keyword: 'leading lines converging to the subject',
    prompt: 'Leading lines composition: rails, road markings and rows of lights in [LOCATION] all converge toward [SUBJECT] standing at the vanishing point in the distance, strong depth, cinematic.',
    pairs: ['symmetry', 'thirds', 'deep-focus'],
    guide: 'lines',
  },
  {
    id: 'silhouette', cat: 'comp', ko: '실루엣', en: 'Silhouette Shot', abbr: 'Silhouette',
    aka: ['역광 샷', '그림자 샷', 'Backlit Shot', 'Contre-jour'],
    media: IMG('silhouette'),
    summary: '강한 역광으로 인물을 검은 형태로만 보여주는 샷.',
    feel: '신비롭고 감성적. 얼굴이 안 보여서 누구나 감정을 투영할 수 있어요.',
    use: '노을·창가 감성 컷, 신비로운 인물 등장, 뮤직비디오, 얼굴을 숨겨야 할 때',
    tip: '배경을 밝게, 인물엔 빛을 주지 마세요. 옆모습·팔 동작처럼 윤곽이 또렷한 포즈가 좋아요.',
    keyword: 'silhouette, strong backlight, subject in pure black',
    prompt: 'Silhouette shot: [SUBJECT] stands in front of a very bright glowing background in [LOCATION], completely backlit so they appear as a pure black shape with a clear outline, moody and mysterious, cinematic.',
    pairs: ['negative-space', 'symmetry', 'anamorphic'],
  },
  {
    id: 'foreground', cat: 'comp', ko: '전경 걸치기', en: 'Foreground Framing', abbr: 'Foreground',
    aka: ['전경 프레이밍', '걸치기 샷', '레이어 구도', 'Dirty Frame'],
    media: IMG('foreground'),
    summary: '카메라 바로 앞에 흐린 사물(나뭇잎·난간·유리)을 걸쳐 깊이를 만드는 구도.',
    feel: '입체감과 엿보는 느낌. 화면이 평평하지 않고 공간 안에 들어간 듯해요.',
    use: '시네마틱 인물 컷, 몰래 지켜보는 시점, 밋밋한 배경 보완, 광고',
    tip: '전경은 화면 가장자리에만, 아주 흐리게. 인물을 가리면 답답해져요.',
    keyword: 'out-of-focus foreground elements framing the subject',
    prompt: 'Foreground framing: shot through out-of-focus leaves and a blurred railing in the near foreground at the frame edges, [SUBJECT] is sharp in the middle distance of [LOCATION], layered depth, cinematic.',
    pairs: ['frame-in-frame', 'shallow-dof', 'truck'],
  },
  {
    id: 'reflection', cat: 'comp', ko: '반사 샷', en: 'Reflection Shot', abbr: 'Reflection',
    aka: ['거울 샷', '물웅덩이 반사', 'Mirror Shot', 'Puddle Reflection'],
    media: IMG('reflection'),
    summary: '물웅덩이·거울·유리창에 비친 인물을 보여주는 샷.',
    feel: '이중성, 내면, 몽환. 현실과 다른 세계를 보는 듯한 시적인 느낌.',
    use: '인물의 내면·고민, 비 오는 날 감성 영상, 장면 전환, 뮤직비디오',
    tip: '반사면이 잔잔해야 또렷해요. 카메라를 반사면 가까이 낮게 두면 반사가 크게 보여요.',
    keyword: 'reflection shot in a puddle',
    prompt: 'Reflection shot: the camera looks down at a still puddle in [LOCATION], [SUBJECT]\'s full upside-down reflection and the city lights are clearly mirrored in the water, dreamy and poetic, cinematic.',
    pairs: ['ground-level', 'symmetry', 'match-cut'],
  },
  {
    id: 'diagonal', cat: 'comp', ko: '대각선 구도', en: 'Diagonal Composition', abbr: 'Diagonal',
    aka: ['사선 구도', '대각 구도', 'Dynamic Diagonal'],
    media: IMG('diagonal'),
    summary: '계단·길·난간을 화면 대각선으로 놓아 움직임을 만드는 구도.',
    feel: '역동적이고 에너지 넘쳐요. 수평 구도보다 긴장감과 속도감이 있어요.',
    use: '뛰거나 오르는 장면, 스포츠, 액션, 지루한 화면에 힘을 줄 때',
    tip: '카메라를 기울이는 더치 앵글과 달라요. 화면 안의 "선"이 대각선이 되도록 위치를 잡으세요.',
    keyword: 'strong diagonal composition',
    prompt: 'Diagonal composition: [SUBJECT] runs up a steep staircase in [LOCATION] that cuts diagonally from the bottom left to the top right of the frame, lights following the diagonal, energetic, cinematic.',
    pairs: ['dutch', 'leading-lines', 'speed-ramp'],
    guide: 'diagonal',
  },
  {
    id: 'headroom', cat: 'comp', ko: '헤드룸 · 룩룸', en: 'Headroom & Lead Room', abbr: 'Headroom',
    aka: ['머리 여백', '시선 여백', 'Nose Room', 'Look Room', '리드 룸'],
    media: CUT(['headroom-bad', 'headroom-good'], 1800, ['나쁜 예', '좋은 예']),
    summary: '머리 위 여백(헤드룸)과 시선 방향 여백(룩룸)을 알맞게 두는 기본 프레이밍.',
    feel: '여백이 맞으면 편안하고 자연스러워요. 틀리면 인물이 가라앉거나 벽에 갇혀 답답해 보여요.',
    use: '거의 모든 인물 샷, 인터뷰, 걷는 장면, 대화 장면',
    tip: '눈은 위쪽 1/3 선에, 바라보는 쪽에 더 넓은 공간을. 일부러 반대로 두면 불안·고립을 표현할 수 있어요.',
    keyword: 'proper headroom, lead room in the direction of the gaze',
    prompt: 'Well-framed medium shot of [SUBJECT] in [LOCATION]: eyes on the upper third line with a little headroom, the subject on the left third looking toward the right with open lead room in front of them, cinematic.',
    pairs: ['thirds', 'mcu', 'negative-space'],
    guide: 'thirds',
  },

  /* ───────────────────────── 인물·대화 ───────────────────────── */
  {
    id: 'ots', cat: 'people', ko: '오버 더 숄더', en: 'Over-the-Shoulder Shot', abbr: 'OTS',
    aka: ['어깨 너머 샷', '숄더 샷', 'OSS'],
    media: IMG('ots'),
    summary: '한 사람의 어깨 너머로 상대방의 얼굴을 보는 대화 샷.',
    feel: '두 사람이 실제로 마주하고 있다는 관계감. 관객이 대화에 함께 참여하는 느낌.',
    use: '대화·인터뷰·면접 장면, 고백·갈등 장면, 샷-리버스 샷 편집',
    tip: '앞사람 어깨는 화면의 1/3을 넘지 않게, 상대는 3분할 선 위에. 반대 방향 샷도 같은 쪽 축(180도 법칙)을 지켜야 해요.',
    keyword: 'over-the-shoulder shot',
    prompt: 'Over-the-shoulder shot: from behind the shoulder of a person in the out-of-focus foreground, looking at [SUBJECT]\'s face as they talk in [LOCATION], natural conversation, shallow depth of field, cinematic.',
    pairs: ['two-shot', 'close-up', 'medium'],
  },
  {
    id: 'two-shot', cat: 'people', ko: '투샷', en: 'Two Shot', abbr: '2S',
    aka: ['투 샷', '2인 샷', 'Two-person Shot'],
    media: IMG('two-shot'),
    summary: '두 사람을 한 화면에 함께 담는 샷.',
    feel: '두 사람의 관계와 거리감, 분위기를 한 번에 보여줘요. 가까우면 친밀, 멀면 어색함.',
    use: '커플·친구 장면, 대화 시작, 두 인물의 관계 소개, 인터뷰 진행자+게스트',
    tip: '두 사람 사이의 물리적 거리가 곧 감정의 거리예요. 높이(앉음/섬)를 다르게 하면 힘의 관계도 보여요.',
    keyword: 'two shot, two people facing each other',
    prompt: 'Two-shot: [SUBJECT] and a second person stand facing each other in profile in [LOCATION], both visible from the knees up, natural conversation and body language, cinematic.',
    pairs: ['ots', 'medium'],
  },
  {
    id: 'pov', cat: 'people', ko: 'POV 샷', en: 'Point of View Shot', abbr: 'POV',
    aka: ['1인칭 시점', '주관적 시점', 'First-person View'],
    media: IMG('pov'),
    summary: '인물의 눈으로 보는 화면. 관객이 그 사람이 돼요.',
    feel: '강한 몰입감과 동일시. "내가 이걸 보고 있다"는 체험형 느낌.',
    use: '체험 영상, 게임·액션, 브이로그 손 샷, 무언가를 발견하는 장면, 인물이 보는 대상 보여주기',
    tip: '앞에 인물의 손·소매가 살짝 보이면 POV 라는 게 확실해져요. 시선 높이와 걸음 흔들림을 사람처럼.',
    keyword: 'first-person POV shot',
    prompt: 'First-person POV shot through the eyes of [SUBJECT]: their hands visible in the lower frame, looking ahead through [LOCATION], natural head movement and eye height, immersive.',
    pairs: ['tracking', 'wide-angle'],
  },
  {
    id: 'shot-reverse', cat: 'people', ko: '샷-리버스 샷', en: 'Shot / Reverse Shot', abbr: 'S/RS',
    aka: ['리버스 샷', '역방향 샷', '대화 편집', 'Shot Reverse Shot', '180도 법칙'],
    media: CUT(['ots', 'srs-b'], 1600, ['A 쪽 샷', 'B 쪽 리버스']),
    summary: '대화하는 두 사람을 서로 반대 방향에서 번갈아 보여주는 편집의 기본.',
    feel: '두 사람이 정말 마주 보고 대화하는 듯한 자연스러운 흐름. 관객이 대화에 끼어 있어요.',
    use: '모든 대화 장면, 인터뷰, 협상·고백·말다툼',
    tip: '두 사람을 잇는 선을 넘지 마세요(180도 법칙). A 는 화면 오른쪽을, B 는 왼쪽을 봐야 해요.',
    keyword: 'shot reverse shot, over-the-shoulder from both sides',
    prompt: 'Shot / reverse shot pair: shot 1 — over the shoulder of a second person looking at [SUBJECT] talking in [LOCATION]; shot 2 — the reverse angle over [SUBJECT]\'s shoulder looking at the second person listening. Keep the 180-degree rule and matching eye lines.',
    pairs: ['ots', 'reaction', 'two-shot'],
  },
  {
    id: 'reaction', cat: 'people', ko: '리액션 샷', en: 'Reaction Shot', abbr: 'Reaction',
    aka: ['반응 샷', '리액션 컷', 'Reaction Cut'],
    media: IMG('reaction'),
    summary: '말하는 사람이 아니라 듣는 사람의 표정·반응을 보여주는 샷.',
    feel: '관객은 리액션을 보고 감정을 느껴요. 대사보다 반응이 더 강하게 전달될 때가 많아요.',
    use: '충격 고백 뒤, 예능 리액션, 공포·감동의 순간, 웃음 포인트',
    tip: '대사가 끝나기 직전이나 직후에 넣으세요. 말없이 1~2초 머물면 감정이 쌓여요.',
    keyword: 'reaction shot, listener\'s emotional response',
    prompt: 'Reaction shot: medium close-up of a person listening in [LOCATION], reacting with surprise and quiet emotion to what [SUBJECT] just said, eyes widening, no dialogue, cinematic.',
    pairs: ['shot-reverse', 'close-up', 'push-in'],
  },
  {
    id: 'group', cat: 'people', ko: '그룹 샷', en: 'Group Shot', abbr: 'Group',
    aka: ['단체 샷', '3인 이상 샷', 'Ensemble Shot', 'Three Shot'],
    media: IMG('group'),
    summary: '세 명 이상을 한 화면에 담아 관계와 분위기를 보여주는 샷.',
    feel: '팀·친구·가족의 유대감. 배치에 따라 리더, 소외된 사람 같은 관계가 보여요.',
    use: '팀·친구 소개, 단체 장면, 광고 엔딩, 축하·파티',
    tip: '모두 일렬로 세우면 지루해요. 높이·앞뒤 거리를 다르게 하고, 주인공을 중앙이나 가장 밝은 곳에.',
    keyword: 'group shot of friends',
    prompt: 'Group shot: [SUBJECT] in the middle of four friends in [LOCATION], all visible from the knees up at different depths and heights, laughing together, natural candid energy, cinematic.',
    pairs: ['two-shot', 'cowboy', 'symmetry'],
  },
  {
    id: 'selfie', cat: 'people', ko: '셀피 샷', en: 'Selfie Shot', abbr: 'Selfie',
    aka: ['셀카 샷', '브이로그 샷', '셀프 촬영', 'Vlog Shot', 'Arm-length'],
    media: IMG('selfie'),
    summary: '인물이 팔을 뻗어 카메라를 직접 들고 자기를 찍는 시점.',
    feel: '친근하고 솔직한 1:1 대화 느낌. 시청자에게 직접 말을 거는 브이로그 감성.',
    use: '브이로그, SNS 광고, UGC 스타일 광고, 여행 리포트',
    tip: '뻗은 팔이 화면 가장자리에 살짝 보여야 셀피 느낌이 나요. 살짝 광각 왜곡이 자연스러워요.',
    keyword: 'selfie shot, handheld at arm\'s length',
    prompt: 'Selfie shot: [SUBJECT] holds the camera at arm\'s length, the outstretched arm visible at the edge of frame, smiling and talking to the lens like a vlogger in [LOCATION], slight wide-angle distortion, natural handheld wobble.',
    pairs: ['pov', 'handheld', 'jump-cut'],
  },
  {
    id: 'walk-talk', cat: 'people', ko: '워크 앤 토크', en: 'Walk and Talk', abbr: 'W&T',
    aka: ['걸으며 대화', '워킹 토크', 'Walk & Talk'],
    media: IMG('walk-talk'), soon: true,
    summary: '두 사람이 걸으며 대화하고, 카메라가 앞에서 뒤로 물러나며 따라가는 샷.',
    feel: '대화에 속도감과 생동감이 생겨요. 정보가 많은 대사도 지루하지 않아요.',
    use: '드라마의 정보 전달 대화, 인터뷰 브이로그, 직장·병원 드라마',
    tip: '카메라는 일정한 속도로 뒤로, 인물은 투샷 크기를 유지. 짐벌이나 스테디캠이 필요해요.',
    keyword: 'walk and talk, camera leading backward',
    prompt: 'Walk and talk: [SUBJECT] and a second person walk side by side toward the camera through [LOCATION], talking and gesturing, the camera moves steadily backward ahead of them keeping a two-shot. One continuous shot, no cuts.',
    pairs: ['tracking', 'two-shot', 'handheld'],
    diagram: { type: 'move', path: 'track' },
  },

  /* ───────────────────────── 렌즈·초점 ───────────────────────── */
  {
    id: 'wide-angle', cat: 'lens', ko: '광각 렌즈', en: 'Wide-angle Lens', abbr: '14~24mm',
    aka: ['초광각', '와이드 렌즈', 'Ultra Wide'],
    media: IMG('wide-angle'),
    summary: '넓게 담기고 가까운 것은 크게, 먼 것은 작게 과장되는 렌즈.',
    feel: '역동적이고 공간이 넓어 보여요. 가까이 다가가면 왜곡으로 코믹하거나 불안한 느낌.',
    use: '좁은 공간을 넓게, 액션·스포츠, 스케이트·댄스, 개성 있는 뮤직비디오',
    tip: '얼굴 가까이에서 쓰면 코가 커지는 왜곡이 생겨요. 인물 미모 컷에는 피하세요.',
    keyword: 'ultra wide-angle 16mm lens, exaggerated perspective',
    prompt: 'Ultra wide-angle 16mm lens very close to [SUBJECT] in [LOCATION]: exaggerated perspective, lines bending outward at the edges, the near hand looks large, dynamic energetic feel, cinematic.',
    pairs: ['low-angle', 'pov', 'dutch'],
  },
  {
    id: 'telephoto', cat: 'lens', ko: '망원 압축', en: 'Telephoto Compression', abbr: '85~200mm',
    aka: ['망원 렌즈', '압축 효과', 'Long Lens'],
    media: IMG('telephoto'),
    summary: '멀리서 망원으로 찍어 배경이 인물 바로 뒤에 붙은 듯 크게 보이는 렌즈.',
    feel: '배경이 압도적으로 크고 빽빽해 보이는 영화적인 화면. 군중 속 고립감, 관찰자 시점.',
    use: '도시·군중 속 인물, 노을·달을 크게, 몰래 지켜보는 시점, 시네마틱 거리 스냅',
    tip: '멀리서 찍어야 해서 공간이 필요해요. AI 에는 200mm telephoto, compressed background 를 함께 쓰세요.',
    keyword: 'telephoto 200mm lens, compressed background',
    prompt: 'Telephoto 200mm lens from far away: the background of [LOCATION] looks huge and stacked tightly right behind [SUBJECT], flattened depth and compressed perspective, cinematic.',
    pairs: ['shallow-dof', 'tracking'],
  },
  {
    id: 'shallow-dof', cat: 'lens', ko: '얕은 심도 (보케)', en: 'Shallow Depth of Field', abbr: 'f/1.4 Bokeh',
    aka: ['아웃포커스', '배경 흐림', '보케', 'Bokeh'],
    media: IMG('shallow-dof'),
    summary: '인물만 선명하고 배경은 동그란 빛망울로 녹아내리는 샷.',
    feel: '시선이 인물에게만 집중되고, 감성적이고 고급스러운 분위기.',
    use: '인물 감정 컷, 뷰티·패션, 제품 클로즈업, 야경 배경의 감성 영상',
    tip: '배경에 작은 불빛이 많을수록 보케가 예뻐요. 너무 얕으면 눈만 초점이 맞고 코가 흐릴 수 있어요.',
    keyword: 'shallow depth of field, 85mm f/1.4, bokeh',
    prompt: 'Shallow depth of field with an 85mm f/1.4 lens: [SUBJECT] is tack sharp while the lights of [LOCATION] melt into large round creamy bokeh circles, cinematic.',
    pairs: ['close-up', 'push-in', 'telephoto'],
  },
  {
    id: 'tilt-shift', cat: 'lens', ko: '틸트시프트 (미니어처)', en: 'Tilt-shift Miniature', abbr: 'Tilt-shift',
    aka: ['미니어처 효과', '장난감 효과', 'Miniature Effect'],
    media: IMG('tilt-shift'),
    summary: '좁은 띠만 초점이 맞고 위아래가 흐려 세상이 장난감처럼 보이는 효과.',
    feel: '귀엽고 동화 같은, 세상을 내려다보는 관찰자 느낌. 타임랩스와 함께 쓰면 장난감 마을처럼.',
    use: '도시·여행 인트로, 타임랩스, 축제·행사 전경, 독특한 장면 전환',
    tip: '높은 곳에서 비스듬히 내려다볼 때만 효과가 살아요. 채도를 조금 높이면 더 장난감 같아요.',
    keyword: 'tilt-shift miniature effect, narrow focus band',
    prompt: 'Tilt-shift miniature effect: high angle view over [LOCATION], only a thin horizontal band where [SUBJECT] stands is in focus, top and bottom heavily blurred, everything looks like tiny toys, saturated colors.',
    pairs: ['time-lapse', 'birds-eye'],
  },
  {
    id: 'rack-focus', cat: 'lens', ko: '랙 포커스', en: 'Rack Focus / Focus Pull', abbr: 'Rack',
    aka: ['초점 이동', '포커스 풀', 'Pull Focus', 'Focus Shift'],
    media: CUT(['rack-a', 'rack-b'], 1300, ['초점: 앞', '초점: 뒤']), soon: true,
    summary: '한 샷 안에서 초점을 앞 → 뒤(또는 뒤 → 앞)로 옮겨 시선을 이동시키는 연출.',
    feel: '"이제 이걸 봐" 하고 관객의 시선을 자연스럽게 안내해요. 깨달음·발견의 순간.',
    use: '앞의 물건 → 인물(관계 연결), 숨어 있던 인물 드러내기, 감성 영상, 제품 광고',
    tip: '얕은 심도(조리개 개방)여야 효과가 커요. AI 에는 focus shifts from ... to ... 를 순서대로 쓰세요.',
    keyword: 'rack focus from the foreground to the background',
    prompt: 'Rack focus: the shot starts focused on raindrops on a glass window in the foreground with [SUBJECT] blurred behind in [LOCATION], then the focus smoothly shifts so the subject becomes sharp and the foreground blurs. One continuous shot, no cuts.',
    pairs: ['shallow-dof', 'foreground', 'push-in'],
  },
  {
    id: 'macro', cat: 'lens', ko: '매크로', en: 'Macro Shot', abbr: 'Macro',
    aka: ['접사', '초근접 촬영', 'Macro Lens', '마이크로'],
    media: IMG('macro'),
    summary: '물방울·눈동자·섬유처럼 아주 작은 것을 화면 가득 크게 찍는 샷.',
    feel: '평소 못 보던 세계를 발견하는 경이로움. 질감과 디테일이 고급스러워요.',
    use: '제품 광고(화장품·시계), 자연 다큐, 음식, 장면 전환 B-roll',
    tip: '초점 범위가 아주 얇아서 조금만 움직여도 흐려져요. 조명을 강하게 주세요.',
    keyword: 'macro shot, extreme detail and texture',
    prompt: 'Macro shot: a single water droplet on [SUBJECT]\'s glossy clothing fills the frame, the droplet reflects tiny lights of [LOCATION], extreme texture detail, razor-thin focus, cinematic.',
    pairs: ['ecu', 'insert', 'shallow-dof'],
  },
  {
    id: 'deep-focus', cat: 'lens', ko: '딥 포커스', en: 'Deep Focus', abbr: 'f/16',
    aka: ['팬 포커스', '깊은 심도', 'Pan Focus', 'Everything in Focus'],
    media: IMG('deep-focus'),
    summary: '가까운 인물부터 먼 배경까지 전부 선명하게 보이는 연출.',
    feel: '관객이 화면 곳곳을 스스로 보게 돼요. 인물과 환경의 관계가 한눈에 드러나요.',
    use: '앞뒤에 다른 인물이 있는 장면(시민 케인), 풍경 속 인물, 건축, 다큐',
    tip: '조리개를 조이고(f/11~16) 광각을 쓰면 쉬워요. AI 에는 everything in sharp focus 를 꼭 넣으세요.',
    keyword: 'deep focus, everything sharp from foreground to background',
    prompt: 'Deep focus: [SUBJECT] is sharp in the foreground on the left and the whole of [LOCATION] is also sharp all the way to the distant background, everything in focus from near to far, f/16, cinematic.',
    pairs: ['wide-angle', 'leading-lines', 'shallow-dof'],
  },
  {
    id: 'fisheye', cat: 'lens', ko: '어안 렌즈', en: 'Fisheye Lens', abbr: '8~15mm',
    aka: ['피시아이', '어안', 'Fisheye', '스케이트 렌즈'],
    media: IMG('fisheye'),
    summary: '180도에 가까운 화각으로 화면이 둥글게 휘는 초광각 렌즈.',
    feel: '장난스럽고 과장되고 에너지 넘쳐요. 90~00년대 스케이트·힙합 뮤직비디오 감성.',
    use: '스케이트·BMX, 힙합 MV, 코믹한 연출, 좁은 공간 전체를 담을 때, 초인종 카메라 시점',
    tip: '가까이 다가갈수록 왜곡이 커져요. 인물 미모 컷이 아니라 개성 컷에 쓰세요.',
    keyword: 'fisheye lens, extreme circular distortion',
    prompt: 'Fisheye lens shot: [SUBJECT] leans close toward the lens, face large in the center, [LOCATION] bends into a round curved shape around them, extreme barrel distortion, playful skate-video energy.',
    pairs: ['wide-angle', 'low-angle', 'handheld'],
  },
  {
    id: 'anamorphic', cat: 'lens', ko: '아나모픽 플레어', en: 'Anamorphic Lens Flare', abbr: '2.39:1',
    aka: ['아나모픽 렌즈', '시네마스코프', '렌즈 플레어', 'Anamorphic', 'Cinemascope'],
    media: IMG('anamorphic'),
    summary: '빛이 가로로 길게 번지는 플레어와 타원형 보케가 생기는 영화용 렌즈.',
    feel: '"영화 같다"는 느낌을 가장 빨리 주는 요소. SF·액션·뮤직비디오의 세련됨.',
    use: '야경·자동차 헤드라이트, SF·액션, 뮤직비디오, 시네마틱 광고',
    tip: '화면 안에 점광원(헤드라이트·가로등)이 있어야 플레어가 생겨요. 과하면 J.J. 에이브럼스 패러디가 돼요.',
    keyword: 'anamorphic lens, horizontal blue lens flares, oval bokeh',
    prompt: 'Anamorphic lens look: long horizontal blue lens flares streak across the frame from bright lights in [LOCATION], oval bokeh, widescreen 2.39:1 cinematic framing, [SUBJECT] in a medium shot.',
    pairs: ['shallow-dof', 'silhouette', 'telephoto'],
  },
  {
    id: 'split-diopter', cat: 'lens', ko: '스플릿 디옵터', en: 'Split Diopter', abbr: 'Split',
    aka: ['분할 초점', '이중 초점', 'Split Focus Diopter'],
    media: IMG('split-diopter'),
    summary: '화면 반쪽은 가까운 인물, 다른 반쪽은 먼 인물에 동시에 초점이 맞는 특수 렌즈 효과.',
    feel: '두 인물이 같은 무게로 보이는 긴장감. 브라이언 드 팔마·타란티노 영화 특유의 낯선 느낌.',
    use: '두 인물의 대립·관계, 스릴러의 감시 장면, 독특한 연출',
    tip: '두 초점 영역 사이의 흐린 경계선에 아무것도 없어야 자연스러워요.',
    keyword: 'split diopter shot, near and far subjects both in focus',
    prompt: 'Split diopter shot: [SUBJECT]\'s face in close-up on the left half of the frame is sharp, and a second person standing far in the background of [LOCATION] on the right half is also sharp, with a soft blurred seam between the halves, tense, cinematic.',
    pairs: ['deep-focus', 'two-shot', 'rack-focus'],
  },

  /* ───────────────────────── 시간·속도 ───────────────────────── */
  {
    id: 'slow-mo', cat: 'time', ko: '슬로모션', en: 'Slow Motion', abbr: '120fps',
    aka: ['슬로우 모션', '고속 촬영', 'Slowmo', 'High Frame Rate'],
    media: VID('slow-mo'),
    summary: '시간을 늘려 순간을 아주 천천히 보여주는 연출.',
    feel: '꿈같고 극적이며 아름다운 느낌. 짧은 순간을 오래 음미하게 만들어요.',
    use: '감정의 절정, 물·머리카락·옷자락의 움직임, 스포츠 결정적 순간, 뷰티·제품 광고',
    tip: '움직임이 있는 대상이어야 효과가 있어요. 실제 촬영은 60fps 이상으로 찍어야 부드러워요.',
    keyword: 'extreme slow motion, 120fps',
    prompt: 'Extreme slow motion, 120fps look: close-up of [SUBJECT] in [LOCATION] as they turn their head, hair and droplets moving through the air very slowly, dreamy and dramatic. One continuous shot, no cuts.',
    pairs: ['close-up', 'orbit', 'speed-ramp'],
  },
  {
    id: 'time-lapse', cat: 'time', ko: '타임랩스', en: 'Time-lapse', abbr: 'Time-lapse',
    aka: ['저속 촬영', '인터벌 촬영', 'Timelapse'],
    media: VID('time-lapse'),
    summary: '긴 시간을 몇 초로 압축해 빠르게 흐르게 보여주는 연출.',
    feel: '시간의 흐름, 도시의 리듬, 변화. 가만히 있는 인물과 빨리 지나가는 세상의 대비.',
    use: '하루의 흐름, 도시 풍경, 구름·노을, 작업 과정, 인물의 고립감 표현',
    tip: '카메라는 반드시 고정(삼각대)해야 해요. 움직이며 찍는 타임랩스는 "하이퍼랩스"예요.',
    keyword: 'time-lapse, locked-off camera, light trails',
    prompt: 'Time-lapse: locked-off static wide shot of [LOCATION]; [SUBJECT] stands perfectly still in the center while people and cars rush past as blurred streaks and light trails, clouds racing across the sky. One continuous shot, no cuts.',
    pairs: ['tilt-shift', 'establishing'],
  },
  {
    id: 'speed-ramp', cat: 'time', ko: '스피드 램프', en: 'Speed Ramp', abbr: 'Ramp',
    aka: ['속도 변화', '램핑', 'Speed Ramping'],
    media: VID('speed-ramp'),
    summary: '한 샷 안에서 빠름 → 슬로모션 → 빠름으로 속도가 바뀌는 연출.',
    feel: '리듬감과 타격감. 결정적 순간을 강조하면서도 지루하지 않아요.',
    use: '스포츠·댄스·액션, 뮤직비디오 비트에 맞춰, 자동차·패션 광고, 쇼츠·릴스',
    tip: '속도가 바뀌는 지점을 음악 비트에 맞추면 훨씬 강렬해요. 실제 촬영은 고프레임으로.',
    keyword: 'speed ramp, fast then slow motion then fast',
    prompt: 'Speed ramp, side tracking view: [SUBJECT] runs through [LOCATION] and leaps; normal fast speed, then dramatically slowing to slow motion mid-air, then snapping back to fast speed on landing. One continuous shot, no cuts.',
    pairs: ['tracking', 'slow-mo'],
  },
  {
    id: 'hyperlapse', cat: 'time', ko: '하이퍼랩스', en: 'Hyperlapse', abbr: 'Hyperlapse',
    aka: ['무빙 타임랩스', '이동 타임랩스', 'Moving Time-lapse'],
    media: IMG('hyperlapse'), soon: true,
    summary: '카메라가 이동하면서 찍는 타임랩스. 공간을 빠르게 날아가는 느낌.',
    feel: '도시를 순간 이동하듯 질주하는 에너지와 시간의 압축.',
    use: '여행·도시 인트로, 출퇴근길, 장소 이동 전환, 광고 오프닝',
    tip: '한 지점(건물·인물)을 계속 화면 중앙에 고정해야 흔들리지 않아요.',
    keyword: 'hyperlapse, moving time-lapse with light trails',
    prompt: 'Hyperlapse: the camera moves steadily forward through [LOCATION] in a fast time-lapse, people and cars streak past as long light trails while [SUBJECT] stays sharp in the center. One continuous shot, no cuts.',
    pairs: ['time-lapse', 'tracking', 'drone'],
  },
  {
    id: 'freeze-frame', cat: 'time', ko: '프리즈 프레임', en: 'Freeze Frame', abbr: 'Freeze',
    aka: ['정지 화면', '스톱 프레임', '인물 소개 정지', 'Still Frame'],
    media: IMG('freeze-frame'),
    summary: '움직이던 화면이 순간 딱 멈추는 연출. 보통 자막이나 내레이션과 함께 써요.',
    feel: '"이게 바로 나야" 하는 위트 있는 인물 소개, 또는 결정적 순간의 강조.',
    use: '인물 소개(이름 자막), 코미디, 영화 엔딩, 스포츠 하이라이트',
    tip: '멈추는 순간의 포즈·표정이 재미있어야 해요. 효과음(찰칵)과 자막을 함께 넣으세요.',
    keyword: 'freeze frame mid-action',
    prompt: 'Freeze frame: [SUBJECT] is frozen mid-jump over a puddle in [LOCATION], splash droplets suspended in the air, slightly desaturated still image with empty space on one side for a name caption.',
    pairs: ['slow-mo', 'jump-cut', 'speed-ramp'],
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'bullet-time', cat: 'time', ko: '불릿 타임', en: 'Bullet Time', abbr: 'Bullet Time',
    aka: ['매트릭스 샷', '타임 슬라이스', 'Time Slice', 'Frozen Moment Orbit'],
    media: IMG('bullet-time'), soon: true,
    summary: '시간이 거의 멈춘 순간을 카메라가 인물 주위를 돌며 보여주는 연출(매트릭스).',
    feel: '초현실적이고 압도적인 "결정적 순간". 시간을 지배하는 느낌.',
    use: '액션의 클라이맥스, 스포츠 점프, 광고의 하이라이트, 뮤직비디오',
    tip: '오빗 + 극단적 슬로모션의 조합이에요. 공중에 멈춘 물방울·파편이 있으면 효과가 커요.',
    keyword: 'bullet time, frozen moment with camera orbiting',
    prompt: 'Bullet time: [SUBJECT] is frozen in mid-air while spinning in [LOCATION], raindrops completely stopped around them like glass beads, while the camera orbits smoothly around the frozen moment. One continuous shot, no cuts.',
    pairs: ['orbit', 'slow-mo', 'freeze-frame'],
    diagram: { type: 'move', path: 'orbit' },
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'reverse', cat: 'time', ko: '역재생', en: 'Reverse Motion', abbr: 'Reverse',
    aka: ['리버스', '거꾸로 재생', 'Rewind', 'Backwards'],
    media: IMG('reverse'), soon: true,
    summary: '시간을 거꾸로 흐르게 해 물방울이 위로 솟고 깨진 것이 붙는 연출.',
    feel: '초현실적이고 신기한 느낌. 회상, 되돌리고 싶은 마음, 마법 같은 순간.',
    use: '뮤직비디오, 회상 장면, 광고의 "짠" 하는 등장, 쇼츠 트릭 영상',
    tip: '물·연기·종이처럼 방향이 분명한 움직임이 있어야 거꾸로인 게 티가 나요.',
    keyword: 'reverse motion, time running backwards',
    prompt: 'Reverse motion: in [LOCATION], rain and a puddle splash fly upward from the ground back into the air while [SUBJECT] stands still looking up in wonder, surreal time running backwards. One continuous shot, no cuts.',
    pairs: ['slow-mo', 'match-cut', 'time-lapse'],
  },

  /* ───────────────────────── 편집·연결 ───────────────────────── */
  {
    id: 'establishing', cat: 'edit', ko: '설정 샷', en: 'Establishing Shot', abbr: 'Est.',
    aka: ['오프닝 샷', '장소 소개 샷', 'Location Shot'],
    media: IMG('establishing'),
    summary: '장면이 시작될 때 "여기가 어디·언제인지" 먼저 보여주는 샷.',
    feel: '관객이 장소와 분위기를 이해하고 이야기 속으로 들어갈 준비를 하게 해요.',
    use: '영상 첫 장면, 장소·시간(낮→밤)이 바뀔 때, 챕터 구분',
    tip: '보통 익스트림 롱 샷이나 드론 샷으로, 2~4초 정도 짧게. 다음 컷은 점점 인물에게 다가가세요.',
    keyword: 'establishing shot, aerial city view',
    prompt: 'Establishing shot: aerial view of [LOCATION] at night, the whole area and atmosphere visible, slow gentle drone movement, no specific person in focus, sets the location and mood, cinematic.',
    pairs: ['extreme-wide', 'pan', 'time-lapse'],
  },
  {
    id: 'match-cut', cat: 'edit', ko: '매치 컷', en: 'Match Cut', abbr: 'Match',
    aka: ['형태 매치', '그래픽 매치', 'Graphic Match'],
    media: { type: 'cut', srcs: ['assets/shots/match-a.webp', 'assets/shots/match-b.webp'], hold: 1600 },
    summary: '비슷한 모양·움직임으로 전혀 다른 두 장면을 자연스럽게 잇는 편집.',
    feel: '두 장면이 연결된 듯한 시적인 울림. "아!" 하는 감탄과 의미의 연결.',
    use: '시간·장소 점프, 상징적 연결(우산 → 달), 감각적인 광고·뮤직비디오 전환',
    tip: '두 컷의 모양·위치·크기가 화면에서 정확히 겹쳐야 해요. AI 에서는 두 장면을 따로 만들고 같은 위치를 지정하세요.',
    keyword: 'match cut, matching circular shape transition',
    prompt: 'Match cut between two shots: shot 1 — top-down view of [SUBJECT] holding a round yellow umbrella, a perfect circle in the center of frame; shot 2 — a full yellow moon, the same circle in the same position and size, above [LOCATION].',
    pairs: ['birds-eye', 'jump-cut'],
  },
  {
    id: 'jump-cut', cat: 'edit', ko: '점프 컷', en: 'Jump Cut', abbr: 'Jump',
    aka: ['점프컷', '시간 점프', 'Time Jump Edit'],
    media: { type: 'cut', srcs: ['assets/shots/jump-1.webp', 'assets/shots/jump-2.webp', 'assets/shots/jump-3.webp'], hold: 900 },
    summary: '같은 구도에서 시간만 건너뛰어 인물이 툭툭 위치를 바꾸는 편집.',
    feel: '시간이 흐르는 지루함·기다림, 또는 빠르고 경쾌한 리듬. 유튜브 특유의 템포.',
    use: '기다림·지루함 표현, 유튜브 토크 편집, 하루 루틴, 코믹한 연출',
    tip: '카메라 위치·구도는 완전히 고정하고 인물만 바뀌어야 해요. 조금이라도 움직이면 실수처럼 보여요.',
    keyword: 'jump cut, locked-off camera, same framing',
    prompt: 'Jump cut sequence: the same locked-off framing of [LOCATION] in three shots; [SUBJECT] appears in a different pose each time (sitting, standing, leaning), time skipping forward between cuts.',
    pairs: ['time-lapse', 'match-cut'],
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'montage', cat: 'edit', ko: '몽타주', en: 'Montage', abbr: 'Montage',
    aka: ['몽타주 시퀀스', '트레이닝 몽타주', 'Montage Sequence'],
    media: CUT(['montage-1', 'montage-2', 'montage-3', 'montage-4'], 800),
    summary: '짧은 컷 여러 개를 음악과 함께 이어 긴 시간·과정을 압축하는 편집.',
    feel: '시간이 흐르고 무언가 쌓여 가는 성장의 느낌. 음악과 함께 감정이 고조돼요.',
    use: '훈련·준비 과정, 하루 일과, 여행 하이라이트, 연애의 시작, 브이로그 오프닝',
    tip: '컷마다 다른 장소·시간이지만 색감·음악으로 통일하세요. 비트에 맞춰 자르면 리듬이 살아요.',
    keyword: 'montage sequence of short shots',
    prompt: 'Montage sequence of four short shots of [SUBJECT] through a day in [LOCATION]: drinking coffee by a window, rushing through a subway station, painting in a studio, celebrating on a rooftop at night. Consistent color grade, edited to music.',
    pairs: ['jump-cut', 'time-lapse', 'cross-cutting'],
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'cutaway', cat: 'edit', ko: '컷어웨이', en: 'Cutaway', abbr: 'Cutaway',
    aka: ['컷 어웨이', '인서트 컷', 'B-roll Cut'],
    media: CUT(['medium', 'cutaway'], 1500, ['대화 장면', '컷어웨이']),
    summary: '진행 중인 장면에서 잠깐 다른 것(시계·창밖·소품)을 보여주고 돌아오는 편집.',
    feel: '정보와 긴장을 더하고, 편집 점을 자연스럽게 숨겨줘요. "시간이 없다"를 말없이 전달.',
    use: '대화 중 시계로 시간 압박, 인터뷰 편집 숨기기, 분위기 설명, 복선',
    tip: '인서트와 비슷하지만 컷어웨이는 "다른 장소·대상"도 돼요. 장면과 관련 있는 것을 고르세요.',
    keyword: 'cutaway to a detail',
    prompt: 'Cutaway: in the middle of a scene of [SUBJECT] talking in [LOCATION], cut away to a close shot of a large analog street clock showing almost midnight, then back to the subject.',
    pairs: ['insert', 'cross-cutting', 'reaction'],
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'cross-cutting', cat: 'edit', ko: '교차 편집', en: 'Cross-cutting', abbr: 'Cross-cut',
    aka: ['평행 편집', '크로스 커팅', 'Parallel Editing', 'Intercutting'],
    media: CUT(['cross-a', 'cross-b'], 1000, ['장소 A', '장소 B']),
    summary: '서로 다른 장소에서 동시에 일어나는 두 사건을 번갈아 보여주는 편집.',
    feel: '"늦지 않을까?" 하는 긴장과 서스펜스. 두 사건이 만날 거라는 기대감.',
    use: '시간에 쫓기는 장면, 구출·추격, 두 인물이 만나기 직전, 비교·대비',
    tip: '컷 길이를 점점 짧게 하면 긴장이 올라가요. 두 장소가 한눈에 구분되게 색감·조명을 다르게.',
    keyword: 'cross-cutting between two locations',
    prompt: 'Cross-cutting sequence: alternate between [SUBJECT] running desperately through [LOCATION] checking a watch, and a subway train with its doors closing on an underground platform where someone waits, cuts getting shorter to build suspense.',
    pairs: ['montage', 'tracking', 'cutaway'],
  },
  {
    draft: true, // 예시 이미지 생성 전 — 이미지가 생기면 이 줄을 지우세요
    id: 'smash-cut', cat: 'edit', ko: '스매시 컷', en: 'Smash Cut', abbr: 'Smash',
    aka: ['충격 컷', '급전환', 'Hard Cut'],
    media: CUT(['smash-a', 'smash-b'], 1500, ['조용한 장면', '갑자기 시끄러운 장면']),
    summary: '조용한 장면에서 갑자기 정반대의 시끄러운 장면으로 툭 끊어 넘어가는 편집.',
    feel: '깜짝 놀람, 웃음, 충격. 분위기의 급반전으로 관객을 깨워요.',
    use: '코미디("절대 안 가" → 가 있음), 악몽에서 깨어남, 광고의 반전, 뮤직비디오 드롭',
    tip: '소리 대비가 핵심이에요. 앞 장면은 아주 조용하게, 뒤 장면은 첫 프레임부터 크게.',
    keyword: 'smash cut from calm silence to loud chaos',
    prompt: 'Smash cut: shot 1 — [SUBJECT] sleeping peacefully in a silent dim bedroom; hard cut to shot 2 — the subject jumping in a packed loud concert crowd with blinding strobe lights and confetti in [LOCATION].',
    pairs: ['jump-cut', 'match-cut', 'speed-ramp'],
  },
  {
    id: 'whip-transition', cat: 'edit', ko: '휩 전환', en: 'Whip Pan Transition', abbr: 'Whip Trans.',
    aka: ['휩 트랜지션', '스위시 전환', 'Swish Transition'],
    media: CUT(['medium', 'whip-pan', 'two-shot'], 800, ['장면 A', '휩 (번짐)', '장면 B']), soon: true,
    summary: '휩 팬의 번짐 속에 컷을 숨겨 다른 장면으로 휙 넘어가는 전환.',
    feel: '빠르고 경쾌하며 장면이 이어진 것 같은 연속감. 쇼츠·여행 영상의 단골.',
    use: '여행지·의상 체인지, 쇼츠·릴스 전환, 뮤직비디오, 액션',
    tip: '앞 장면 끝과 다음 장면 시작의 휩 방향·속도를 똑같이 맞추세요.',
    keyword: 'whip pan transition between two scenes',
    prompt: 'Whip pan transition: shot 1 ends with a fast whip pan to the right away from [SUBJECT] into horizontal motion blur; shot 2 starts with the same fast whip pan landing on [SUBJECT] in a different part of [LOCATION]. The cut is hidden in the blur.',
    pairs: ['whip-pan', 'match-cut', 'montage'],
  },
  {
    id: 'dissolve', cat: 'edit', ko: '디졸브', en: 'Dissolve / Cross-fade', abbr: 'Dissolve',
    aka: ['오버랩', '크로스페이드', 'Cross Dissolve', 'Fade'],
    media: { ...CUT(['close-up', 'extreme-wide'], 1800), fade: true },
    summary: '앞 장면이 서서히 사라지며 다음 장면과 겹쳐 바뀌는 전환.',
    feel: '부드럽고 서정적이에요. 시간이 흘렀다, 생각에 잠겼다, 회상한다는 느낌.',
    use: '시간 경과, 회상, 감성 영상, 뮤직비디오, 다큐의 장면 연결',
    tip: '너무 자주 쓰면 올드해 보여요. 두 장면의 밝은 부분과 어두운 부분이 겹치게 하면 아름다워요.',
    keyword: 'slow dissolve between two shots',
    prompt: 'Slow dissolve: a close-up of [SUBJECT]\'s face gradually fades and overlaps into an extreme wide shot of [LOCATION], the two images blending for a moment, dreamy passage of time.',
    pairs: ['match-cut', 'montage', 'establishing'],
  },
];
