/* 영상 샷 도감 — 샷 데이터
   샷 1개 = 객체 1개. 카드 · 상세보기 · AI 프롬프트 · 샷 조합기가 모두 이 데이터에서 만들어집니다.

   필드
   - id / cat          URL 해시용 id (shots.html#low-angle), 분류 id (SHOT_CATEGORIES)
   - ko / en / abbr    한글 이름 / 영문 이름 / 약어
   - aka               다른 이름(검색 키워드)
   - media             { type: 'image', src } | { type: 'video', src, poster } | { type: 'cut', srcs: [...] } (컷 전환 시퀀스)
   - summary           카드 한 줄 설명
   - feel              화면이 주는 느낌·효과
   - use               언제 쓰면 좋은지
   - tip               주의점
   - keyword           AI 영상 도구에 넣을 핵심 영어 키워드 (샷 조합기에서도 사용)
   - prompt            완성 영어 프롬프트. [SUBJECT] [LOCATION] 은 상세보기에서 원하는 대상·장소로 바뀝니다.
   - pairs             잘 어울리는 다른 샷 id
   - diagram           카메라 배치 도식 (size / angle / move) — 선택
   - guide             구도 가이드 선 (thirds / center / frame / space) — 선택 */

window.SHOT_CATEGORIES = [
  { id: 'size', ko: '샷 크기', en: 'Shot Size' },
  { id: 'angle', ko: '카메라 앵글', en: 'Camera Angle' },
  { id: 'move', ko: '카메라 무빙', en: 'Camera Movement' },
  { id: 'comp', ko: '구도·프레이밍', en: 'Composition' },
  { id: 'people', ko: '인물·대화', en: 'People & Dialogue' },
  { id: 'lens', ko: '렌즈·초점', en: 'Lens & Focus' },
  { id: 'time', ko: '시간·속도', en: 'Time & Speed' },
  { id: 'edit', ko: '편집·연결', en: 'Editing' },
];

const IMG = (id) => ({ type: 'image', src: 'assets/shots/' + id + '.webp' });
const VID = (id) => ({ type: 'video', src: 'assets/shots/' + id + '.mp4', poster: 'assets/shots/' + id + '.webp' });

window.SHOTS = [
  /* ───────────────────────── 샷 크기 ───────────────────────── */
  {
    id: 'extreme-wide', cat: 'size', ko: '익스트림 롱 샷', en: 'Extreme Wide Shot', abbr: 'EWS / ELS',
    aka: ['익스트림 와이드', 'Extreme Long Shot', '초원경'],
    media: IMG('extreme-wide'),
    summary: '인물은 아주 작고, 장소와 공간의 규모가 주인공이 되는 샷.',
    feel: '압도적인 스케일, 고독함, "여기가 어디인지"를 한눈에 알려줘요. 인물이 작을수록 세상에 비해 작고 외로워 보여요.',
    use: '영상 첫 장면, 장소가 바뀔 때, 여행·풍경 영상, 인물의 고립감을 보여줄 때',
    tip: '인물이 너무 작으면 누군지 모를 수 있어요. 옷 색(노란 우비처럼)으로 눈에 띄게 하고, 길게 보여주지 마세요.',
    keyword: 'extreme wide shot',
    prompt: 'Extreme wide shot from a high vantage point: [SUBJECT] appears very small in the center of the frame, dwarfed by [LOCATION]. Emphasize vast scale and atmosphere, cinematic lighting, slow and calm.',
    pairs: ['establishing', 'birds-eye', 'push-in'],
    diagram: { type: 'size', top: -1.6, bottom: 2.4 },
  },
  {
    id: 'full', cat: 'size', ko: '풀 샷', en: 'Full Shot', abbr: 'FS',
    aka: ['전신 샷', 'Wide Shot', 'Long Shot', '롱 샷'],
    media: { type: 'image', src: 'assets/shots/full.webp' },
    summary: '머리부터 발끝까지 인물 전체가 프레임에 딱 들어오는 샷.',
    feel: '인물의 옷차림·자세·몸짓과 주변 공간을 함께 보여줘요. 감정보다는 "이 사람이 이곳에 있다"는 상황 설명에 가까워요.',
    use: '인물 첫 등장, 의상·패션 영상, 춤·운동처럼 몸 전체 동작이 중요한 장면',
    tip: '발끝이 잘리지 않게 아래 여백을 조금 두세요. 머리 위 여백이 너무 크면 인물이 가라앉아 보여요.',
    keyword: 'full shot, full body in frame',
    prompt: 'Full shot showing [SUBJECT] from head to toe, standing in [LOCATION], eye-level camera, the whole body and outfit clearly visible with a little space around, cinematic composition.',
    pairs: ['medium', 'tracking', 'thirds'],
    diagram: { type: 'size', top: -0.08, bottom: 1.08 },
  },
  {
    id: 'medium', cat: 'size', ko: '미디엄 샷', en: 'Medium Shot', abbr: 'MS',
    aka: ['허리 샷', 'Waist Shot', '바스트 샷 이전'],
    media: IMG('medium'),
    summary: '허리 위부터 머리까지, 가장 일상적이고 자연스러운 거리의 샷.',
    feel: '대화하는 사람과 마주한 듯 편안한 거리감. 표정과 손짓이 모두 보여서 정보 전달에 좋아요.',
    use: '인터뷰, 유튜브 토크, 대화 장면, 제품을 손에 들고 설명할 때',
    tip: '관절(허리·팔꿈치) 바로 위에서 자르면 어색해요. 허리 살짝 아래나 위에서 자르세요.',
    keyword: 'medium shot, waist up',
    prompt: 'Medium shot of [SUBJECT] from the waist up in [LOCATION], eye level, natural expression and hand gestures visible, background softly out of focus, cinematic.',
    pairs: ['two-shot', 'ots', 'shallow-dof'],
    diagram: { type: 'size', top: -0.06, bottom: 0.52 },
  },
  {
    id: 'close-up', cat: 'size', ko: '클로즈업', en: 'Close-up', abbr: 'CU',
    aka: ['얼굴 샷', '근접 샷', 'Tight Shot'],
    media: IMG('close-up'),
    summary: '얼굴(또는 대상)이 화면을 가득 채우는 샷. 감정이 가장 잘 보여요.',
    feel: '감정 몰입, 긴장감, 친밀함. 관객이 인물의 마음속으로 들어가는 느낌을 줘요.',
    use: '감정이 터지는 순간, 중요한 대사, 리액션, 제품 디테일 강조',
    tip: '너무 자주 쓰면 효과가 떨어져요. 넓은 샷 사이에 결정적인 순간에만 넣으세요.',
    keyword: 'close-up shot of the face',
    prompt: 'Close-up shot of [SUBJECT]\'s face filling the frame in [LOCATION], subtle emotional expression, detailed skin and texture, soft cinematic light on the face, shallow depth of field.',
    pairs: ['push-in', 'slow-mo', 'shallow-dof'],
    diagram: { type: 'size', top: -0.04, bottom: 0.22 },
  },

  /* ───────────────────────── 카메라 앵글 ───────────────────────── */
  {
    id: 'high-angle', cat: 'angle', ko: '하이 앵글', en: 'High Angle', abbr: 'HA',
    aka: ['부감', '내려다보기', 'Looking Down'],
    media: IMG('high-angle'),
    summary: '카메라가 인물보다 높은 곳에서 내려다보는 샷.',
    feel: '인물이 작고 약해 보여요. 외로움, 무력감, 관찰당하는 느낌, 또는 귀여움을 줄 수 있어요.',
    use: '인물이 위기에 처했을 때, 패배·좌절 장면, 아이·반려동물을 귀엽게, 상황 전체를 내려다볼 때',
    tip: '각도가 너무 크면(거의 수직) 버즈아이 뷰가 돼요. 감정을 담으려면 30~45도 정도가 좋아요.',
    keyword: 'high angle shot, camera looking down',
    prompt: 'High angle shot: the camera is above [SUBJECT] looking down at about 45 degrees in [LOCATION], the subject looks up toward the camera and appears small and vulnerable, cinematic.',
    pairs: ['negative-space', 'close-up'],
    diagram: { type: 'angle', cam: 'high' },
  },
  {
    id: 'low-angle', cat: 'angle', ko: '로우 앵글', en: 'Low Angle', abbr: 'LA',
    aka: ['앙각', '올려다보기', 'Looking Up', 'Hero Shot'],
    media: IMG('low-angle'),
    summary: '카메라가 낮은 곳에서 인물을 올려다보는 샷.',
    feel: '인물이 크고 강하고 위압적으로 보여요. 자신감, 권위, 영웅적인 느낌.',
    use: '주인공 등장, 승리·결심의 순간, 악역의 위압감, 제품·건물을 웅장하게',
    tip: '광각 렌즈로 너무 가까이서 찍으면 얼굴(턱·코)이 왜곡돼요. 조금 떨어져서 찍으세요.',
    keyword: 'low angle shot, camera looking up',
    prompt: 'Low angle hero shot: the camera is near knee height looking up at [SUBJECT] in [LOCATION], the subject towers over the camera, powerful and confident, dramatic sky and tall background, cinematic.',
    pairs: ['slow-mo', 'push-in', 'wide-angle'],
    diagram: { type: 'angle', cam: 'low' },
  },
  {
    id: 'birds-eye', cat: 'angle', ko: '버즈아이 뷰', en: "Bird's-eye View", abbr: 'Top Shot',
    aka: ['탑 뷰', '오버헤드 샷', 'Overhead Shot', '부감 수직'],
    media: IMG('birds-eye'),
    summary: '카메라가 바로 위에서 수직으로 내려다보는 샷.',
    feel: '지도나 무대처럼 그래픽적인 화면. 신의 시점, 운명, 패턴의 아름다움을 보여줘요.',
    use: '음식·책상 위 플랫레이, 도시·도로 패턴, 인물의 위치 관계, 장면 전환용',
    tip: '그림자와 색 대비가 강해야 평면적이지 않아요. 드론이나 높은 곳에서 수직을 정확히 맞추세요.',
    keyword: "bird's-eye view, top-down overhead shot",
    prompt: "Bird's-eye view: the camera is directly overhead looking straight down at [SUBJECT] in [LOCATION], graphic top-down composition, strong shapes, shadows and color contrast, cinematic.",
    pairs: ['extreme-wide', 'match-cut', 'tilt-shift'],
    diagram: { type: 'angle', cam: 'top' },
  },
  {
    id: 'dutch', cat: 'angle', ko: '더치 앵글', en: 'Dutch Angle', abbr: 'Dutch Tilt',
    aka: ['캔티드 앵글', 'Canted Angle', '기울인 화면', '사선 구도'],
    media: IMG('dutch'),
    summary: '카메라를 옆으로 기울여 수평선이 사선이 되는 샷.',
    feel: '불안, 혼란, 긴장, 뭔가 잘못된 느낌. 세상이 기울어진 듯한 심리 상태를 표현해요.',
    use: '스릴러·호러, 인물이 혼란스럽거나 취했을 때, 뮤직비디오의 역동적인 연출',
    tip: '남발하면 어지럽고 촌스러워 보여요. 감정이 흔들리는 장면에만 쓰고 기울기는 10~25도가 적당해요.',
    keyword: 'dutch angle, canted tilted camera',
    prompt: 'Dutch angle shot: the camera is tilted about 20 degrees so the horizon and lines of [LOCATION] run diagonally, [SUBJECT] looks tense and uneasy, disorienting psychological mood, cinematic.',
    pairs: ['close-up', 'jump-cut', 'wide-angle'],
    diagram: { type: 'angle', cam: 'tilt' },
  },

  /* ───────────────────────── 카메라 무빙 ───────────────────────── */
  {
    id: 'push-in', cat: 'move', ko: '푸시 인 (달리 인)', en: 'Push In / Dolly In', abbr: 'Dolly In',
    aka: ['달리 인', '카메라 전진', 'Slow Push', '트랙 인'],
    media: VID('push-in'),
    summary: '카메라가 인물 쪽으로 천천히 다가가는 무빙.',
    feel: '긴장과 집중이 점점 커져요. 인물의 깨달음, 결심, 감정의 고조를 관객이 함께 느끼게 해요.',
    use: '중요한 대사·깨달음의 순간, 인물 소개, 광고 마지막 제품 강조',
    tip: '줌(Zoom)과 달라요. 줌은 렌즈만 당겨 원근감이 그대로지만, 푸시인은 카메라가 실제로 움직여 배경과의 거리감이 변해요.',
    keyword: 'slow dolly push-in',
    prompt: 'Slow dolly push-in: the camera moves steadily forward from a full shot toward [SUBJECT]\'s face in [LOCATION], ending in a close-up. Smooth cinematic camera move, one continuous shot, no cuts.',
    pairs: ['close-up', 'low-angle', 'shallow-dof'],
    diagram: { type: 'move', path: 'push' },
  },
  {
    id: 'pan', cat: 'move', ko: '팬', en: 'Pan', abbr: 'Pan L/R',
    aka: ['패닝', '좌우 회전', 'Panning Shot'],
    media: VID('pan'),
    summary: '카메라 위치는 고정한 채 좌우로 고개를 돌리는 무빙.',
    feel: '관객이 고개를 돌려 주변을 둘러보는 느낌. 공간을 소개하거나 무언가를 "발견"하게 만들어요.',
    use: '풍경·공간 소개, 인물이나 물건을 드러내는(리빌) 장면, 움직이는 대상 따라가기',
    tip: '카메라가 옆으로 "이동"하면 트럭(Truck), 제자리에서 "회전"하면 팬이에요. AI 에는 fixed position, rotates 처럼 명확히 쓰세요.',
    keyword: 'slow pan left to right, fixed camera position',
    prompt: 'Slow horizontal camera pan from left to right on a fixed tripod: the shot starts on [LOCATION] and pans to reveal [SUBJECT]. The camera position stays fixed and only rotates. One continuous shot, no cuts.',
    pairs: ['extreme-wide', 'establishing'],
    diagram: { type: 'move', path: 'pan' },
  },
  {
    id: 'tracking', cat: 'move', ko: '트래킹 샷', en: 'Tracking Shot', abbr: 'Follow Shot',
    aka: ['팔로우 샷', '추적 샷', 'Follow Cam', '리딩 샷'],
    media: VID('tracking'),
    summary: '걷거나 달리는 인물과 같은 속도로 카메라가 함께 이동하는 무빙.',
    feel: '관객이 인물과 함께 걷는 듯한 몰입감과 생동감. 이야기가 앞으로 나아가는 느낌.',
    use: '걸으며 말하는 장면, 브이로그, 추격·이동 장면, 패션 런웨이',
    tip: '앞에서 뒤로 물러나며 찍으면 "리딩", 뒤에서 따라가면 "팔로우"예요. 짐벌·스테디캠으로 흔들림을 줄이세요.',
    keyword: 'tracking shot, camera moves backward with the walking subject',
    prompt: 'Tracking shot: the camera moves backward in front of [SUBJECT] at walking pace as the subject walks toward the camera through [LOCATION], keeping them medium-full in frame, steady gimbal movement. One continuous shot, no cuts.',
    pairs: ['full', 'speed-ramp'],
    diagram: { type: 'move', path: 'track' },
  },
  {
    id: 'orbit', cat: 'move', ko: '오빗 샷', en: 'Orbit / Arc Shot', abbr: 'Arc',
    aka: ['아크 샷', '360 샷', '회전 샷', 'Circle Shot'],
    media: VID('orbit'),
    summary: '카메라가 인물 주위를 원을 그리며 도는 무빙.',
    feel: '인물이 세계의 중심이 된 듯한 극적인 순간. 감정의 절정, 히어로 모먼트에 강해요.',
    use: '주인공의 결정적 순간, 재회·고백, 제품 360도 소개, 뮤직비디오',
    tip: '배경이 회전해야 효과가 커요. 인물 뒤에 조명·간판 같은 포인트가 있으면 회전이 잘 보여요.',
    keyword: 'orbit shot, camera circles around the subject',
    prompt: 'Orbit shot: the camera circles smoothly about 180 degrees around [SUBJECT] at eye level while they stand still in [LOCATION]; the background rotates behind them. Smooth arc camera movement, one continuous shot, no cuts.',
    pairs: ['low-angle', 'slow-mo'],
    diagram: { type: 'move', path: 'orbit' },
  },

  /* ───────────────────────── 구도·프레이밍 ───────────────────────── */
  {
    id: 'thirds', cat: 'comp', ko: '3분할 구도', en: 'Rule of Thirds', abbr: 'Thirds',
    aka: ['삼분할', '황금분할 비슷', 'Off-center Framing'],
    media: IMG('thirds'),
    summary: '화면을 가로·세로 3등분한 선 위에 인물을 두는 가장 기본 구도.',
    feel: '안정적이면서도 정중앙보다 자연스럽고 여유 있는 느낌. 인물이 바라보는 쪽에 공간이 생겨요.',
    use: '대부분의 인물·풍경 샷, 인터뷰, 인물이 무언가를 바라보는 장면',
    tip: '인물이 바라보는(또는 걸어가는) 방향에 빈 공간(룩 룸)을 두세요. 반대로 두면 답답하고 불안해 보여요.',
    keyword: 'rule of thirds composition, subject on the left third',
    prompt: 'Rule-of-thirds composition: [SUBJECT] stands on the left vertical third line of the frame in [LOCATION], with open space and leading light toward the right two thirds, cinematic.',
    pairs: ['full', 'negative-space'],
    guide: 'thirds',
  },
  {
    id: 'symmetry', cat: 'comp', ko: '중앙 대칭 구도', en: 'Symmetrical Composition', abbr: 'Center',
    aka: ['대칭 구도', '센터 프레이밍', '웨스 앤더슨 구도', 'Centered Framing'],
    media: IMG('symmetry'),
    summary: '인물을 정중앙에, 양쪽 배경을 거울처럼 맞춘 구도.',
    feel: '단단하고 의도적인 느낌, 정적인 긴장감, 동화나 그림 같은 미장센.',
    use: '인물 소개 엔딩 컷, 건축·인테리어, 스타일리시한 광고, 정면 대치 장면',
    tip: '조금만 어긋나도 실수처럼 보여요. 수평·수직을 정확히 맞추고, 소실점을 인물 뒤에 두세요.',
    keyword: 'perfectly symmetrical centered composition',
    prompt: 'Perfectly symmetrical centered composition: [SUBJECT] stands exactly in the center of [LOCATION], the background mirrored on both sides, the vanishing point directly behind the subject, static camera, cinematic.',
    pairs: ['push-in', 'establishing'],
    guide: 'center',
  },
  {
    id: 'frame-in-frame', cat: 'comp', ko: '프레임 속 프레임', en: 'Frame within a Frame', abbr: 'FiF',
    aka: ['액자 구도', '이중 프레임', 'Natural Frame'],
    media: IMG('frame-in-frame'),
    summary: '문·창문·터널 같은 사물로 인물을 한 번 더 둘러싸는 구도.',
    feel: '시선이 인물에게 집중되고, 엿보는 듯한 관음적 느낌이나 갇힌 느낌, 깊이감을 줘요.',
    use: '인물을 관찰하는 시점, 고립·갇힘 표현, 공간의 깊이를 보여줄 때',
    tip: '앞쪽 프레임(문틀)은 어둡게, 인물 쪽은 밝게 하면 시선이 확실히 모여요.',
    keyword: 'frame within a frame, shot through a doorway',
    prompt: 'Frame within a frame: shot from inside a dark interior through a doorway or window; the bright opening frames [SUBJECT] standing in [LOCATION] beyond, strong depth and contrast, cinematic.',
    pairs: ['negative-space', 'symmetry'],
    guide: 'frame',
  },
  {
    id: 'negative-space', cat: 'comp', ko: '네거티브 스페이스', en: 'Negative Space', abbr: 'Empty Space',
    aka: ['여백 구도', '빈 공간', 'Minimal Composition'],
    media: IMG('negative-space'),
    summary: '인물은 작게 구석에, 화면 대부분을 비워 두는 구도.',
    feel: '고요함, 외로움, 그리움, 생각에 잠긴 느낌. 빈 공간이 감정을 대신 말해요.',
    use: '감성 영상, 이별·그리움 장면, 자막·카피를 넣을 공간이 필요한 광고',
    tip: '빈 공간에도 질감(하늘·안개·빛)이 있어야 허전하지 않아요. 글자를 넣을 자리로도 좋아요.',
    keyword: 'negative space composition, small subject in the corner',
    prompt: 'Minimal negative space composition: [SUBJECT] is small in the lower right corner, a large empty area of [LOCATION] fills the rest of the frame, quiet and lonely mood, cinematic.',
    pairs: ['extreme-wide', 'high-angle'],
    guide: 'space',
  },

  /* ───────────────────────── 인물·대화 ───────────────────────── */
  {
    id: 'ots', cat: 'people', ko: '오버 더 숄더', en: 'Over-the-Shoulder Shot', abbr: 'OTS',
    aka: ['어깨 너머 샷', '숄더 샷', 'OSS'],
    media: IMG('ots'),
    summary: '한 사람의 어깨 너머로 상대방의 얼굴을 보는 대화 샷.',
    feel: '두 사람이 실제로 마주하고 있다는 관계감. 관객이 대화에 함께 참여하는 느낌.',
    use: '대화·인터뷰·면접 장면, 고백·갈등 장면, 샷-리버스 샷 편집',
    tip: '앞사람 어깨는 화면의 1/3을 넘지 않게, 상대는 3분할 선 위에. 반대 방향 샷도 같은 쪽 축(180도 법칙)을 지켜야 해요.',
    keyword: 'over-the-shoulder shot',
    prompt: 'Over-the-shoulder shot: from behind the shoulder of a person in the out-of-focus foreground, looking at [SUBJECT]\'s face as they talk in [LOCATION], natural conversation, shallow depth of field, cinematic.',
    pairs: ['two-shot', 'close-up', 'medium'],
  },
  {
    id: 'two-shot', cat: 'people', ko: '투샷', en: 'Two Shot', abbr: '2S',
    aka: ['투 샷', '2인 샷', 'Two-person Shot'],
    media: IMG('two-shot'),
    summary: '두 사람을 한 화면에 함께 담는 샷.',
    feel: '두 사람의 관계와 거리감, 분위기를 한 번에 보여줘요. 가까우면 친밀, 멀면 어색함.',
    use: '커플·친구 장면, 대화 시작, 두 인물의 관계 소개, 인터뷰 진행자+게스트',
    tip: '두 사람 사이의 물리적 거리가 곧 감정의 거리예요. 높이(앉음/섬)를 다르게 하면 힘의 관계도 보여요.',
    keyword: 'two shot, two people facing each other',
    prompt: 'Two-shot: [SUBJECT] and a second person stand facing each other in profile in [LOCATION], both visible from the knees up, natural conversation and body language, cinematic.',
    pairs: ['ots', 'medium'],
  },
  {
    id: 'pov', cat: 'people', ko: 'POV 샷', en: 'Point of View Shot', abbr: 'POV',
    aka: ['1인칭 시점', '주관적 시점', 'First-person View'],
    media: IMG('pov'),
    summary: '인물의 눈으로 보는 화면. 관객이 그 사람이 돼요.',
    feel: '강한 몰입감과 동일시. "내가 이걸 보고 있다"는 체험형 느낌.',
    use: '체험 영상, 게임·액션, 브이로그 손 샷, 무언가를 발견하는 장면, 인물이 보는 대상 보여주기',
    tip: '앞에 인물의 손·소매가 살짝 보이면 POV 라는 게 확실해져요. 시선 높이와 걸음 흔들림을 사람처럼.',
    keyword: 'first-person POV shot',
    prompt: 'First-person POV shot through the eyes of [SUBJECT]: their hands visible in the lower frame, looking ahead through [LOCATION], natural head movement and eye height, immersive.',
    pairs: ['tracking', 'wide-angle'],
  },

  /* ───────────────────────── 렌즈·초점 ───────────────────────── */
  {
    id: 'wide-angle', cat: 'lens', ko: '광각 렌즈', en: 'Wide-angle Lens', abbr: '14~24mm',
    aka: ['초광각', '와이드 렌즈', 'Ultra Wide'],
    media: IMG('wide-angle'),
    summary: '넓게 담기고 가까운 것은 크게, 먼 것은 작게 과장되는 렌즈.',
    feel: '역동적이고 공간이 넓어 보여요. 가까이 다가가면 왜곡으로 코믹하거나 불안한 느낌.',
    use: '좁은 공간을 넓게, 액션·스포츠, 스케이트·댄스, 개성 있는 뮤직비디오',
    tip: '얼굴 가까이에서 쓰면 코가 커지는 왜곡이 생겨요. 인물 미모 컷에는 피하세요.',
    keyword: 'ultra wide-angle 16mm lens, exaggerated perspective',
    prompt: 'Ultra wide-angle 16mm lens very close to [SUBJECT] in [LOCATION]: exaggerated perspective, lines bending outward at the edges, the near hand looks large, dynamic energetic feel, cinematic.',
    pairs: ['low-angle', 'pov', 'dutch'],
  },
  {
    id: 'telephoto', cat: 'lens', ko: '망원 압축', en: 'Telephoto Compression', abbr: '85~200mm',
    aka: ['망원 렌즈', '압축 효과', 'Long Lens'],
    media: IMG('telephoto'),
    summary: '멀리서 망원으로 찍어 배경이 인물 바로 뒤에 붙은 듯 크게 보이는 렌즈.',
    feel: '배경이 압도적으로 크고 빽빽해 보이는 영화적인 화면. 군중 속 고립감, 관찰자 시점.',
    use: '도시·군중 속 인물, 노을·달을 크게, 몰래 지켜보는 시점, 시네마틱 거리 스냅',
    tip: '멀리서 찍어야 해서 공간이 필요해요. AI 에는 200mm telephoto, compressed background 를 함께 쓰세요.',
    keyword: 'telephoto 200mm lens, compressed background',
    prompt: 'Telephoto 200mm lens from far away: the background of [LOCATION] looks huge and stacked tightly right behind [SUBJECT], flattened depth and compressed perspective, cinematic.',
    pairs: ['shallow-dof', 'tracking'],
  },
  {
    id: 'shallow-dof', cat: 'lens', ko: '얕은 심도 (보케)', en: 'Shallow Depth of Field', abbr: 'f/1.4 Bokeh',
    aka: ['아웃포커스', '배경 흐림', '보케', 'Bokeh'],
    media: IMG('shallow-dof'),
    summary: '인물만 선명하고 배경은 동그란 빛망울로 녹아내리는 샷.',
    feel: '시선이 인물에게만 집중되고, 감성적이고 고급스러운 분위기.',
    use: '인물 감정 컷, 뷰티·패션, 제품 클로즈업, 야경 배경의 감성 영상',
    tip: '배경에 작은 불빛이 많을수록 보케가 예뻐요. 너무 얕으면 눈만 초점이 맞고 코가 흐릴 수 있어요.',
    keyword: 'shallow depth of field, 85mm f/1.4, bokeh',
    prompt: 'Shallow depth of field with an 85mm f/1.4 lens: [SUBJECT] is tack sharp while the lights of [LOCATION] melt into large round creamy bokeh circles, cinematic.',
    pairs: ['close-up', 'push-in', 'telephoto'],
  },
  {
    id: 'tilt-shift', cat: 'lens', ko: '틸트시프트 (미니어처)', en: 'Tilt-shift Miniature', abbr: 'Tilt-shift',
    aka: ['미니어처 효과', '장난감 효과', 'Miniature Effect'],
    media: IMG('tilt-shift'),
    summary: '좁은 띠만 초점이 맞고 위아래가 흐려 세상이 장난감처럼 보이는 효과.',
    feel: '귀엽고 동화 같은, 세상을 내려다보는 관찰자 느낌. 타임랩스와 함께 쓰면 장난감 마을처럼.',
    use: '도시·여행 인트로, 타임랩스, 축제·행사 전경, 독특한 장면 전환',
    tip: '높은 곳에서 비스듬히 내려다볼 때만 효과가 살아요. 채도를 조금 높이면 더 장난감 같아요.',
    keyword: 'tilt-shift miniature effect, narrow focus band',
    prompt: 'Tilt-shift miniature effect: high angle view over [LOCATION], only a thin horizontal band where [SUBJECT] stands is in focus, top and bottom heavily blurred, everything looks like tiny toys, saturated colors.',
    pairs: ['time-lapse', 'birds-eye'],
  },

  /* ───────────────────────── 시간·속도 ───────────────────────── */
  {
    id: 'slow-mo', cat: 'time', ko: '슬로모션', en: 'Slow Motion', abbr: '120fps',
    aka: ['슬로우 모션', '고속 촬영', 'Slowmo', 'High Frame Rate'],
    media: VID('slow-mo'),
    summary: '시간을 늘려 순간을 아주 천천히 보여주는 연출.',
    feel: '꿈같고 극적이며 아름다운 느낌. 짧은 순간을 오래 음미하게 만들어요.',
    use: '감정의 절정, 물·머리카락·옷자락의 움직임, 스포츠 결정적 순간, 뷰티·제품 광고',
    tip: '움직임이 있는 대상이어야 효과가 있어요. 실제 촬영은 60fps 이상으로 찍어야 부드러워요.',
    keyword: 'extreme slow motion, 120fps',
    prompt: 'Extreme slow motion, 120fps look: close-up of [SUBJECT] in [LOCATION] as they turn their head, hair and droplets moving through the air very slowly, dreamy and dramatic. One continuous shot, no cuts.',
    pairs: ['close-up', 'orbit', 'speed-ramp'],
  },
  {
    id: 'time-lapse', cat: 'time', ko: '타임랩스', en: 'Time-lapse', abbr: 'Time-lapse',
    aka: ['저속 촬영', '인터벌 촬영', 'Timelapse'],
    media: VID('time-lapse'),
    summary: '긴 시간을 몇 초로 압축해 빠르게 흐르게 보여주는 연출.',
    feel: '시간의 흐름, 도시의 리듬, 변화. 가만히 있는 인물과 빨리 지나가는 세상의 대비.',
    use: '하루의 흐름, 도시 풍경, 구름·노을, 작업 과정, 인물의 고립감 표현',
    tip: '카메라는 반드시 고정(삼각대)해야 해요. 움직이며 찍는 타임랩스는 "하이퍼랩스"예요.',
    keyword: 'time-lapse, locked-off camera, light trails',
    prompt: 'Time-lapse: locked-off static wide shot of [LOCATION]; [SUBJECT] stands perfectly still in the center while people and cars rush past as blurred streaks and light trails, clouds racing across the sky. One continuous shot, no cuts.',
    pairs: ['tilt-shift', 'establishing'],
  },
  {
    id: 'speed-ramp', cat: 'time', ko: '스피드 램프', en: 'Speed Ramp', abbr: 'Ramp',
    aka: ['속도 변화', '램핑', 'Speed Ramping'],
    media: VID('speed-ramp'),
    summary: '한 샷 안에서 빠름 → 슬로모션 → 빠름으로 속도가 바뀌는 연출.',
    feel: '리듬감과 타격감. 결정적 순간을 강조하면서도 지루하지 않아요.',
    use: '스포츠·댄스·액션, 뮤직비디오 비트에 맞춰, 자동차·패션 광고, 쇼츠·릴스',
    tip: '속도가 바뀌는 지점을 음악 비트에 맞추면 훨씬 강렬해요. 실제 촬영은 고프레임으로.',
    keyword: 'speed ramp, fast then slow motion then fast',
    prompt: 'Speed ramp, side tracking view: [SUBJECT] runs through [LOCATION] and leaps; normal fast speed, then dramatically slowing to slow motion mid-air, then snapping back to fast speed on landing. One continuous shot, no cuts.',
    pairs: ['tracking', 'slow-mo'],
  },

  /* ───────────────────────── 편집·연결 ───────────────────────── */
  {
    id: 'establishing', cat: 'edit', ko: '설정 샷', en: 'Establishing Shot', abbr: 'Est.',
    aka: ['오프닝 샷', '장소 소개 샷', 'Location Shot'],
    media: IMG('establishing'),
    summary: '장면이 시작될 때 "여기가 어디·언제인지" 먼저 보여주는 샷.',
    feel: '관객이 장소와 분위기를 이해하고 이야기 속으로 들어갈 준비를 하게 해요.',
    use: '영상 첫 장면, 장소·시간(낮→밤)이 바뀔 때, 챕터 구분',
    tip: '보통 익스트림 롱 샷이나 드론 샷으로, 2~4초 정도 짧게. 다음 컷은 점점 인물에게 다가가세요.',
    keyword: 'establishing shot, aerial city view',
    prompt: 'Establishing shot: aerial view of [LOCATION] at night, the whole area and atmosphere visible, slow gentle drone movement, no specific person in focus, sets the location and mood, cinematic.',
    pairs: ['extreme-wide', 'pan', 'time-lapse'],
  },
  {
    id: 'match-cut', cat: 'edit', ko: '매치 컷', en: 'Match Cut', abbr: 'Match',
    aka: ['형태 매치', '그래픽 매치', 'Graphic Match'],
    media: { type: 'cut', srcs: ['assets/shots/match-a.webp', 'assets/shots/match-b.webp'], hold: 1600 },
    summary: '비슷한 모양·움직임으로 전혀 다른 두 장면을 자연스럽게 잇는 편집.',
    feel: '두 장면이 연결된 듯한 시적인 울림. "아!" 하는 감탄과 의미의 연결.',
    use: '시간·장소 점프, 상징적 연결(우산 → 달), 감각적인 광고·뮤직비디오 전환',
    tip: '두 컷의 모양·위치·크기가 화면에서 정확히 겹쳐야 해요. AI 에서는 두 장면을 따로 만들고 같은 위치를 지정하세요.',
    keyword: 'match cut, matching circular shape transition',
    prompt: 'Match cut between two shots: shot 1 — top-down view of [SUBJECT] holding a round yellow umbrella, a perfect circle in the center of frame; shot 2 — a full yellow moon, the same circle in the same position and size, above [LOCATION].',
    pairs: ['birds-eye', 'jump-cut'],
  },
  {
    id: 'jump-cut', cat: 'edit', ko: '점프 컷', en: 'Jump Cut', abbr: 'Jump',
    aka: ['점프컷', '시간 점프', 'Time Jump Edit'],
    media: { type: 'cut', srcs: ['assets/shots/jump-1.webp', 'assets/shots/jump-2.webp', 'assets/shots/jump-3.webp'], hold: 900 },
    summary: '같은 구도에서 시간만 건너뛰어 인물이 툭툭 위치를 바꾸는 편집.',
    feel: '시간이 흐르는 지루함·기다림, 또는 빠르고 경쾌한 리듬. 유튜브 특유의 템포.',
    use: '기다림·지루함 표현, 유튜브 토크 편집, 하루 루틴, 코믹한 연출',
    tip: '카메라 위치·구도는 완전히 고정하고 인물만 바뀌어야 해요. 조금이라도 움직이면 실수처럼 보여요.',
    keyword: 'jump cut, locked-off camera, same framing',
    prompt: 'Jump cut sequence: the same locked-off framing of [LOCATION] in three shots; [SUBJECT] appears in a different pose each time (sitting, standing, leaning), time skipping forward between cuts.',
    pairs: ['time-lapse', 'match-cut'],
  },
];
